// Code generated by ent, DO NOT EDIT.

package votingsession

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the votingsession type in the database.
	Label = "voting_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeAwards holds the string denoting the awards edge name in mutations.
	EdgeAwards = "awards"
	// EdgeVoteItems holds the string denoting the vote_items edge name in mutations.
	EdgeVoteItems = "vote_items"
	// Table holds the table name of the votingsession in the database.
	Table = "voting_sessions"
	// AwardsTable is the table that holds the awards relation/edge.
	AwardsTable = "awards"
	// AwardsInverseTable is the table name for the Award entity.
	// It exists in this package in order to avoid circular dependency with the "award" package.
	AwardsInverseTable = "awards"
	// AwardsColumn is the table column denoting the awards relation/edge.
	AwardsColumn = "voting_session_awards"
	// VoteItemsTable is the table that holds the vote_items relation/edge.
	VoteItemsTable = "vote_items"
	// VoteItemsInverseTable is the table name for the VoteItem entity.
	// It exists in this package in order to avoid circular dependency with the "voteitem" package.
	VoteItemsInverseTable = "vote_items"
	// VoteItemsColumn is the table column denoting the vote_items relation/edge.
	VoteItemsColumn = "voting_session_vote_items"
)

// Columns holds all SQL columns for votingsession fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldYear,
	FieldName,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending   Status = "pending"
	StatusActive    Status = "active"
	StatusCounting  Status = "counting"
	StatusPublished Status = "published"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusActive, StatusCounting, StatusPublished:
		return nil
	default:
		return fmt.Errorf("votingsession: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the VotingSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByYear orders the results by the year field.
func ByYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYear, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAwardsCount orders the results by awards count.
func ByAwardsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAwardsStep(), opts...)
	}
}

// ByAwards orders the results by awards terms.
func ByAwards(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAwardsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByVoteItemsCount orders the results by vote_items count.
func ByVoteItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVoteItemsStep(), opts...)
	}
}

// ByVoteItems orders the results by vote_items terms.
func ByVoteItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVoteItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAwardsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AwardsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AwardsTable, AwardsColumn),
	)
}
func newVoteItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VoteItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VoteItemsTable, VoteItemsColumn),
	)
}
