// Code generated by ent, DO NOT EDIT.

package nominee

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the nominee type in the database.
	Label = "nominee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCoverImageKey holds the string denoting the cover_image_key field in the database.
	FieldCoverImageKey = "cover_image_key"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldDisplayOrder holds the string denoting the display_order field in the database.
	FieldDisplayOrder = "display_order"
	// FieldBangumiID holds the string denoting the bangumi_id field in the database.
	FieldBangumiID = "bangumi_id"
	// FieldRelatedBangumiID holds the string denoting the related_bangumi_id field in the database.
	FieldRelatedBangumiID = "related_bangumi_id"
	// FieldRelatedName holds the string denoting the related_name field in the database.
	FieldRelatedName = "related_name"
	// FieldRelatedImageURL holds the string denoting the related_image_url field in the database.
	FieldRelatedImageURL = "related_image_url"
	// EdgeAward holds the string denoting the award edge name in mutations.
	EdgeAward = "award"
	// EdgeVoteItems holds the string denoting the vote_items edge name in mutations.
	EdgeVoteItems = "vote_items"
	// Table holds the table name of the nominee in the database.
	Table = "nominees"
	// AwardTable is the table that holds the award relation/edge.
	AwardTable = "nominees"
	// AwardInverseTable is the table name for the Award entity.
	// It exists in this package in order to avoid circular dependency with the "award" package.
	AwardInverseTable = "awards"
	// AwardColumn is the table column denoting the award relation/edge.
	AwardColumn = "award_nominees"
	// VoteItemsTable is the table that holds the vote_items relation/edge.
	VoteItemsTable = "vote_items"
	// VoteItemsInverseTable is the table name for the VoteItem entity.
	// It exists in this package in order to avoid circular dependency with the "voteitem" package.
	VoteItemsInverseTable = "vote_items"
	// VoteItemsColumn is the table column denoting the vote_items relation/edge.
	VoteItemsColumn = "nominee_vote_items"
)

// Columns holds all SQL columns for nominee fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldCoverImageKey,
	FieldDescription,
	FieldDisplayOrder,
	FieldBangumiID,
	FieldRelatedBangumiID,
	FieldRelatedName,
	FieldRelatedImageURL,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "nominees"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"award_nominees",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDisplayOrder holds the default value on creation for the "display_order" field.
	DefaultDisplayOrder int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Nominee queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCoverImageKey orders the results by the cover_image_key field.
func ByCoverImageKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverImageKey, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByDisplayOrder orders the results by the display_order field.
func ByDisplayOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayOrder, opts...).ToFunc()
}

// ByBangumiID orders the results by the bangumi_id field.
func ByBangumiID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBangumiID, opts...).ToFunc()
}

// ByRelatedBangumiID orders the results by the related_bangumi_id field.
func ByRelatedBangumiID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelatedBangumiID, opts...).ToFunc()
}

// ByRelatedName orders the results by the related_name field.
func ByRelatedName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelatedName, opts...).ToFunc()
}

// ByRelatedImageURL orders the results by the related_image_url field.
func ByRelatedImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelatedImageURL, opts...).ToFunc()
}

// ByAwardField orders the results by award field.
func ByAwardField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAwardStep(), sql.OrderByField(field, opts...))
	}
}

// ByVoteItemsCount orders the results by vote_items count.
func ByVoteItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVoteItemsStep(), opts...)
	}
}

// ByVoteItems orders the results by vote_items terms.
func ByVoteItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVoteItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAwardStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AwardInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AwardTable, AwardColumn),
	)
}
func newVoteItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VoteItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VoteItemsTable, VoteItemsColumn),
	)
}
