// Code generated by ent, DO NOT EDIT.

package nominee

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Nominee {
	return predicate.Nominee(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Nominee {
	return predicate.Nominee(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Nominee {
	return predicate.Nominee(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Nominee {
	return predicate.Nominee(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Nominee {
	return predicate.Nominee(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Nominee {
	return predicate.Nominee(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Nominee {
	return predicate.Nominee(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldName, v))
}

// CoverImageKey applies equality check predicate on the "cover_image_key" field. It's identical to CoverImageKeyEQ.
func CoverImageKey(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldCoverImageKey, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldDescription, v))
}

// DisplayOrder applies equality check predicate on the "display_order" field. It's identical to DisplayOrderEQ.
func DisplayOrder(v int) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldDisplayOrder, v))
}

// BangumiID applies equality check predicate on the "bangumi_id" field. It's identical to BangumiIDEQ.
func BangumiID(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldBangumiID, v))
}

// RelatedBangumiID applies equality check predicate on the "related_bangumi_id" field. It's identical to RelatedBangumiIDEQ.
func RelatedBangumiID(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldRelatedBangumiID, v))
}

// RelatedName applies equality check predicate on the "related_name" field. It's identical to RelatedNameEQ.
func RelatedName(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldRelatedName, v))
}

// RelatedImageURL applies equality check predicate on the "related_image_url" field. It's identical to RelatedImageURLEQ.
func RelatedImageURL(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldRelatedImageURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Nominee {
	return predicate.Nominee(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContainsFold(FieldName, v))
}

// CoverImageKeyEQ applies the EQ predicate on the "cover_image_key" field.
func CoverImageKeyEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldCoverImageKey, v))
}

// CoverImageKeyNEQ applies the NEQ predicate on the "cover_image_key" field.
func CoverImageKeyNEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNEQ(FieldCoverImageKey, v))
}

// CoverImageKeyIn applies the In predicate on the "cover_image_key" field.
func CoverImageKeyIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldIn(FieldCoverImageKey, vs...))
}

// CoverImageKeyNotIn applies the NotIn predicate on the "cover_image_key" field.
func CoverImageKeyNotIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNotIn(FieldCoverImageKey, vs...))
}

// CoverImageKeyGT applies the GT predicate on the "cover_image_key" field.
func CoverImageKeyGT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGT(FieldCoverImageKey, v))
}

// CoverImageKeyGTE applies the GTE predicate on the "cover_image_key" field.
func CoverImageKeyGTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGTE(FieldCoverImageKey, v))
}

// CoverImageKeyLT applies the LT predicate on the "cover_image_key" field.
func CoverImageKeyLT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLT(FieldCoverImageKey, v))
}

// CoverImageKeyLTE applies the LTE predicate on the "cover_image_key" field.
func CoverImageKeyLTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLTE(FieldCoverImageKey, v))
}

// CoverImageKeyContains applies the Contains predicate on the "cover_image_key" field.
func CoverImageKeyContains(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContains(FieldCoverImageKey, v))
}

// CoverImageKeyHasPrefix applies the HasPrefix predicate on the "cover_image_key" field.
func CoverImageKeyHasPrefix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasPrefix(FieldCoverImageKey, v))
}

// CoverImageKeyHasSuffix applies the HasSuffix predicate on the "cover_image_key" field.
func CoverImageKeyHasSuffix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasSuffix(FieldCoverImageKey, v))
}

// CoverImageKeyIsNil applies the IsNil predicate on the "cover_image_key" field.
func CoverImageKeyIsNil() predicate.Nominee {
	return predicate.Nominee(sql.FieldIsNull(FieldCoverImageKey))
}

// CoverImageKeyNotNil applies the NotNil predicate on the "cover_image_key" field.
func CoverImageKeyNotNil() predicate.Nominee {
	return predicate.Nominee(sql.FieldNotNull(FieldCoverImageKey))
}

// CoverImageKeyEqualFold applies the EqualFold predicate on the "cover_image_key" field.
func CoverImageKeyEqualFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEqualFold(FieldCoverImageKey, v))
}

// CoverImageKeyContainsFold applies the ContainsFold predicate on the "cover_image_key" field.
func CoverImageKeyContainsFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContainsFold(FieldCoverImageKey, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Nominee {
	return predicate.Nominee(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Nominee {
	return predicate.Nominee(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContainsFold(FieldDescription, v))
}

// DisplayOrderEQ applies the EQ predicate on the "display_order" field.
func DisplayOrderEQ(v int) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldDisplayOrder, v))
}

// DisplayOrderNEQ applies the NEQ predicate on the "display_order" field.
func DisplayOrderNEQ(v int) predicate.Nominee {
	return predicate.Nominee(sql.FieldNEQ(FieldDisplayOrder, v))
}

// DisplayOrderIn applies the In predicate on the "display_order" field.
func DisplayOrderIn(vs ...int) predicate.Nominee {
	return predicate.Nominee(sql.FieldIn(FieldDisplayOrder, vs...))
}

// DisplayOrderNotIn applies the NotIn predicate on the "display_order" field.
func DisplayOrderNotIn(vs ...int) predicate.Nominee {
	return predicate.Nominee(sql.FieldNotIn(FieldDisplayOrder, vs...))
}

// DisplayOrderGT applies the GT predicate on the "display_order" field.
func DisplayOrderGT(v int) predicate.Nominee {
	return predicate.Nominee(sql.FieldGT(FieldDisplayOrder, v))
}

// DisplayOrderGTE applies the GTE predicate on the "display_order" field.
func DisplayOrderGTE(v int) predicate.Nominee {
	return predicate.Nominee(sql.FieldGTE(FieldDisplayOrder, v))
}

// DisplayOrderLT applies the LT predicate on the "display_order" field.
func DisplayOrderLT(v int) predicate.Nominee {
	return predicate.Nominee(sql.FieldLT(FieldDisplayOrder, v))
}

// DisplayOrderLTE applies the LTE predicate on the "display_order" field.
func DisplayOrderLTE(v int) predicate.Nominee {
	return predicate.Nominee(sql.FieldLTE(FieldDisplayOrder, v))
}

// BangumiIDEQ applies the EQ predicate on the "bangumi_id" field.
func BangumiIDEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldBangumiID, v))
}

// BangumiIDNEQ applies the NEQ predicate on the "bangumi_id" field.
func BangumiIDNEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNEQ(FieldBangumiID, v))
}

// BangumiIDIn applies the In predicate on the "bangumi_id" field.
func BangumiIDIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldIn(FieldBangumiID, vs...))
}

// BangumiIDNotIn applies the NotIn predicate on the "bangumi_id" field.
func BangumiIDNotIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNotIn(FieldBangumiID, vs...))
}

// BangumiIDGT applies the GT predicate on the "bangumi_id" field.
func BangumiIDGT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGT(FieldBangumiID, v))
}

// BangumiIDGTE applies the GTE predicate on the "bangumi_id" field.
func BangumiIDGTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGTE(FieldBangumiID, v))
}

// BangumiIDLT applies the LT predicate on the "bangumi_id" field.
func BangumiIDLT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLT(FieldBangumiID, v))
}

// BangumiIDLTE applies the LTE predicate on the "bangumi_id" field.
func BangumiIDLTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLTE(FieldBangumiID, v))
}

// BangumiIDContains applies the Contains predicate on the "bangumi_id" field.
func BangumiIDContains(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContains(FieldBangumiID, v))
}

// BangumiIDHasPrefix applies the HasPrefix predicate on the "bangumi_id" field.
func BangumiIDHasPrefix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasPrefix(FieldBangumiID, v))
}

// BangumiIDHasSuffix applies the HasSuffix predicate on the "bangumi_id" field.
func BangumiIDHasSuffix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasSuffix(FieldBangumiID, v))
}

// BangumiIDIsNil applies the IsNil predicate on the "bangumi_id" field.
func BangumiIDIsNil() predicate.Nominee {
	return predicate.Nominee(sql.FieldIsNull(FieldBangumiID))
}

// BangumiIDNotNil applies the NotNil predicate on the "bangumi_id" field.
func BangumiIDNotNil() predicate.Nominee {
	return predicate.Nominee(sql.FieldNotNull(FieldBangumiID))
}

// BangumiIDEqualFold applies the EqualFold predicate on the "bangumi_id" field.
func BangumiIDEqualFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEqualFold(FieldBangumiID, v))
}

// BangumiIDContainsFold applies the ContainsFold predicate on the "bangumi_id" field.
func BangumiIDContainsFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContainsFold(FieldBangumiID, v))
}

// RelatedBangumiIDEQ applies the EQ predicate on the "related_bangumi_id" field.
func RelatedBangumiIDEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldRelatedBangumiID, v))
}

// RelatedBangumiIDNEQ applies the NEQ predicate on the "related_bangumi_id" field.
func RelatedBangumiIDNEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNEQ(FieldRelatedBangumiID, v))
}

// RelatedBangumiIDIn applies the In predicate on the "related_bangumi_id" field.
func RelatedBangumiIDIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldIn(FieldRelatedBangumiID, vs...))
}

// RelatedBangumiIDNotIn applies the NotIn predicate on the "related_bangumi_id" field.
func RelatedBangumiIDNotIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNotIn(FieldRelatedBangumiID, vs...))
}

// RelatedBangumiIDGT applies the GT predicate on the "related_bangumi_id" field.
func RelatedBangumiIDGT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGT(FieldRelatedBangumiID, v))
}

// RelatedBangumiIDGTE applies the GTE predicate on the "related_bangumi_id" field.
func RelatedBangumiIDGTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGTE(FieldRelatedBangumiID, v))
}

// RelatedBangumiIDLT applies the LT predicate on the "related_bangumi_id" field.
func RelatedBangumiIDLT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLT(FieldRelatedBangumiID, v))
}

// RelatedBangumiIDLTE applies the LTE predicate on the "related_bangumi_id" field.
func RelatedBangumiIDLTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLTE(FieldRelatedBangumiID, v))
}

// RelatedBangumiIDContains applies the Contains predicate on the "related_bangumi_id" field.
func RelatedBangumiIDContains(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContains(FieldRelatedBangumiID, v))
}

// RelatedBangumiIDHasPrefix applies the HasPrefix predicate on the "related_bangumi_id" field.
func RelatedBangumiIDHasPrefix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasPrefix(FieldRelatedBangumiID, v))
}

// RelatedBangumiIDHasSuffix applies the HasSuffix predicate on the "related_bangumi_id" field.
func RelatedBangumiIDHasSuffix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasSuffix(FieldRelatedBangumiID, v))
}

// RelatedBangumiIDIsNil applies the IsNil predicate on the "related_bangumi_id" field.
func RelatedBangumiIDIsNil() predicate.Nominee {
	return predicate.Nominee(sql.FieldIsNull(FieldRelatedBangumiID))
}

// RelatedBangumiIDNotNil applies the NotNil predicate on the "related_bangumi_id" field.
func RelatedBangumiIDNotNil() predicate.Nominee {
	return predicate.Nominee(sql.FieldNotNull(FieldRelatedBangumiID))
}

// RelatedBangumiIDEqualFold applies the EqualFold predicate on the "related_bangumi_id" field.
func RelatedBangumiIDEqualFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEqualFold(FieldRelatedBangumiID, v))
}

// RelatedBangumiIDContainsFold applies the ContainsFold predicate on the "related_bangumi_id" field.
func RelatedBangumiIDContainsFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContainsFold(FieldRelatedBangumiID, v))
}

// RelatedNameEQ applies the EQ predicate on the "related_name" field.
func RelatedNameEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldRelatedName, v))
}

// RelatedNameNEQ applies the NEQ predicate on the "related_name" field.
func RelatedNameNEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNEQ(FieldRelatedName, v))
}

// RelatedNameIn applies the In predicate on the "related_name" field.
func RelatedNameIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldIn(FieldRelatedName, vs...))
}

// RelatedNameNotIn applies the NotIn predicate on the "related_name" field.
func RelatedNameNotIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNotIn(FieldRelatedName, vs...))
}

// RelatedNameGT applies the GT predicate on the "related_name" field.
func RelatedNameGT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGT(FieldRelatedName, v))
}

// RelatedNameGTE applies the GTE predicate on the "related_name" field.
func RelatedNameGTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGTE(FieldRelatedName, v))
}

// RelatedNameLT applies the LT predicate on the "related_name" field.
func RelatedNameLT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLT(FieldRelatedName, v))
}

// RelatedNameLTE applies the LTE predicate on the "related_name" field.
func RelatedNameLTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLTE(FieldRelatedName, v))
}

// RelatedNameContains applies the Contains predicate on the "related_name" field.
func RelatedNameContains(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContains(FieldRelatedName, v))
}

// RelatedNameHasPrefix applies the HasPrefix predicate on the "related_name" field.
func RelatedNameHasPrefix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasPrefix(FieldRelatedName, v))
}

// RelatedNameHasSuffix applies the HasSuffix predicate on the "related_name" field.
func RelatedNameHasSuffix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasSuffix(FieldRelatedName, v))
}

// RelatedNameIsNil applies the IsNil predicate on the "related_name" field.
func RelatedNameIsNil() predicate.Nominee {
	return predicate.Nominee(sql.FieldIsNull(FieldRelatedName))
}

// RelatedNameNotNil applies the NotNil predicate on the "related_name" field.
func RelatedNameNotNil() predicate.Nominee {
	return predicate.Nominee(sql.FieldNotNull(FieldRelatedName))
}

// RelatedNameEqualFold applies the EqualFold predicate on the "related_name" field.
func RelatedNameEqualFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEqualFold(FieldRelatedName, v))
}

// RelatedNameContainsFold applies the ContainsFold predicate on the "related_name" field.
func RelatedNameContainsFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContainsFold(FieldRelatedName, v))
}

// RelatedImageURLEQ applies the EQ predicate on the "related_image_url" field.
func RelatedImageURLEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEQ(FieldRelatedImageURL, v))
}

// RelatedImageURLNEQ applies the NEQ predicate on the "related_image_url" field.
func RelatedImageURLNEQ(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNEQ(FieldRelatedImageURL, v))
}

// RelatedImageURLIn applies the In predicate on the "related_image_url" field.
func RelatedImageURLIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldIn(FieldRelatedImageURL, vs...))
}

// RelatedImageURLNotIn applies the NotIn predicate on the "related_image_url" field.
func RelatedImageURLNotIn(vs ...string) predicate.Nominee {
	return predicate.Nominee(sql.FieldNotIn(FieldRelatedImageURL, vs...))
}

// RelatedImageURLGT applies the GT predicate on the "related_image_url" field.
func RelatedImageURLGT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGT(FieldRelatedImageURL, v))
}

// RelatedImageURLGTE applies the GTE predicate on the "related_image_url" field.
func RelatedImageURLGTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldGTE(FieldRelatedImageURL, v))
}

// RelatedImageURLLT applies the LT predicate on the "related_image_url" field.
func RelatedImageURLLT(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLT(FieldRelatedImageURL, v))
}

// RelatedImageURLLTE applies the LTE predicate on the "related_image_url" field.
func RelatedImageURLLTE(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldLTE(FieldRelatedImageURL, v))
}

// RelatedImageURLContains applies the Contains predicate on the "related_image_url" field.
func RelatedImageURLContains(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContains(FieldRelatedImageURL, v))
}

// RelatedImageURLHasPrefix applies the HasPrefix predicate on the "related_image_url" field.
func RelatedImageURLHasPrefix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasPrefix(FieldRelatedImageURL, v))
}

// RelatedImageURLHasSuffix applies the HasSuffix predicate on the "related_image_url" field.
func RelatedImageURLHasSuffix(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldHasSuffix(FieldRelatedImageURL, v))
}

// RelatedImageURLIsNil applies the IsNil predicate on the "related_image_url" field.
func RelatedImageURLIsNil() predicate.Nominee {
	return predicate.Nominee(sql.FieldIsNull(FieldRelatedImageURL))
}

// RelatedImageURLNotNil applies the NotNil predicate on the "related_image_url" field.
func RelatedImageURLNotNil() predicate.Nominee {
	return predicate.Nominee(sql.FieldNotNull(FieldRelatedImageURL))
}

// RelatedImageURLEqualFold applies the EqualFold predicate on the "related_image_url" field.
func RelatedImageURLEqualFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldEqualFold(FieldRelatedImageURL, v))
}

// RelatedImageURLContainsFold applies the ContainsFold predicate on the "related_image_url" field.
func RelatedImageURLContainsFold(v string) predicate.Nominee {
	return predicate.Nominee(sql.FieldContainsFold(FieldRelatedImageURL, v))
}

// HasAward applies the HasEdge predicate on the "award" edge.
func HasAward() predicate.Nominee {
	return predicate.Nominee(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AwardTable, AwardColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAwardWith applies the HasEdge predicate on the "award" edge with a given conditions (other predicates).
func HasAwardWith(preds ...predicate.Award) predicate.Nominee {
	return predicate.Nominee(func(s *sql.Selector) {
		step := newAwardStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVoteItems applies the HasEdge predicate on the "vote_items" edge.
func HasVoteItems() predicate.Nominee {
	return predicate.Nominee(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VoteItemsTable, VoteItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVoteItemsWith applies the HasEdge predicate on the "vote_items" edge with a given conditions (other predicates).
func HasVoteItemsWith(preds ...predicate.VoteItem) predicate.Nominee {
	return predicate.Nominee(func(s *sql.Selector) {
		step := newVoteItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Nominee) predicate.Nominee {
	return predicate.Nominee(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Nominee) predicate.Nominee {
	return predicate.Nominee(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Nominee) predicate.Nominee {
	return predicate.Nominee(sql.NotPredicates(p))
}
