// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/award"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/nominee"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/schema"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/school"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/voteitem"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/votingsession"
)

// AwardCreate is the builder for creating a Award entity.
type AwardCreate struct {
	config
	mutation *AwardMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AwardCreate) SetCreatedAt(v time.Time) *AwardCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AwardCreate) SetNillableCreatedAt(v *time.Time) *AwardCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AwardCreate) SetUpdatedAt(v time.Time) *AwardCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AwardCreate) SetNillableUpdatedAt(v *time.Time) *AwardCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AwardCreate) SetName(v string) *AwardCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AwardCreate) SetDescription(v string) *AwardCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AwardCreate) SetNillableDescription(v *string) *AwardCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *AwardCreate) SetCategory(v award.Category) *AwardCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetType sets the "type" field.
func (_c *AwardCreate) SetType(v award.Type) *AwardCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *AwardCreate) SetNillableType(v *award.Type) *AwardCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetScoreConfig sets the "score_config" field.
func (_c *AwardCreate) SetScoreConfig(v schema.ScoreConfig) *AwardCreate {
	_c.mutation.SetScoreConfig(v)
	return _c
}

// SetDisplayOrder sets the "display_order" field.
func (_c *AwardCreate) SetDisplayOrder(v int) *AwardCreate {
	_c.mutation.SetDisplayOrder(v)
	return _c
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_c *AwardCreate) SetNillableDisplayOrder(v *int) *AwardCreate {
	if v != nil {
		_c.SetDisplayOrder(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AwardCreate) SetID(v uuid.UUID) *AwardCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AwardCreate) SetNillableID(v *uuid.UUID) *AwardCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSessionID sets the "session" edge to the VotingSession entity by ID.
func (_c *AwardCreate) SetSessionID(id uuid.UUID) *AwardCreate {
	_c.mutation.SetSessionID(id)
	return _c
}

// SetSession sets the "session" edge to the VotingSession entity.
func (_c *AwardCreate) SetSession(v *VotingSession) *AwardCreate {
	return _c.SetSessionID(v.ID)
}

// SetSchoolID sets the "school" edge to the School entity by ID.
func (_c *AwardCreate) SetSchoolID(id uuid.UUID) *AwardCreate {
	_c.mutation.SetSchoolID(id)
	return _c
}

// SetNillableSchoolID sets the "school" edge to the School entity by ID if the given value is not nil.
func (_c *AwardCreate) SetNillableSchoolID(id *uuid.UUID) *AwardCreate {
	if id != nil {
		_c = _c.SetSchoolID(*id)
	}
	return _c
}

// SetSchool sets the "school" edge to the School entity.
func (_c *AwardCreate) SetSchool(v *School) *AwardCreate {
	return _c.SetSchoolID(v.ID)
}

// AddNomineeIDs adds the "nominees" edge to the Nominee entity by IDs.
func (_c *AwardCreate) AddNomineeIDs(ids ...uuid.UUID) *AwardCreate {
	_c.mutation.AddNomineeIDs(ids...)
	return _c
}

// AddNominees adds the "nominees" edges to the Nominee entity.
func (_c *AwardCreate) AddNominees(v ...*Nominee) *AwardCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNomineeIDs(ids...)
}

// AddVoteItemIDs adds the "vote_items" edge to the VoteItem entity by IDs.
func (_c *AwardCreate) AddVoteItemIDs(ids ...uuid.UUID) *AwardCreate {
	_c.mutation.AddVoteItemIDs(ids...)
	return _c
}

// AddVoteItems adds the "vote_items" edges to the VoteItem entity.
func (_c *AwardCreate) AddVoteItems(v ...*VoteItem) *AwardCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVoteItemIDs(ids...)
}

// Mutation returns the AwardMutation object of the builder.
func (_c *AwardCreate) Mutation() *AwardMutation {
	return _c.mutation
}

// Save creates the Award in the database.
func (_c *AwardCreate) Save(ctx context.Context) (*Award, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AwardCreate) SaveX(ctx context.Context) *Award {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AwardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AwardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AwardCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := award.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := award.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := award.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		v := award.DefaultDisplayOrder
		_c.mutation.SetDisplayOrder(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := award.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AwardCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Award.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Award.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Award.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := award.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Award.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Award.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := award.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Award.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Award.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := award.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Award.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScoreConfig(); !ok {
		return &ValidationError{Name: "score_config", err: errors.New(`ent: missing required field "Award.score_config"`)}
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`ent: missing required field "Award.display_order"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "Award.session"`)}
	}
	return nil
}

func (_c *AwardCreate) sqlSave(ctx context.Context) (*Award, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AwardCreate) createSpec() (*Award, *sqlgraph.CreateSpec) {
	var (
		_node = &Award{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(award.Table, sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(award.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(award.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(award.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(award.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(award.FieldCategory, field.TypeEnum, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(award.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.ScoreConfig(); ok {
		_spec.SetField(award.FieldScoreConfig, field.TypeJSON, value)
		_node.ScoreConfig = value
	}
	if value, ok := _c.mutation.DisplayOrder(); ok {
		_spec.SetField(award.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   award.SessionTable,
			Columns: []string{award.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.voting_session_awards = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SchoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   award.SchoolTable,
			Columns: []string{award.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.school_awards = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NomineesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.NomineesTable,
			Columns: []string{award.NomineesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VoteItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.VoteItemsTable,
			Columns: []string{award.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AwardCreateBulk is the builder for creating many Award entities in bulk.
type AwardCreateBulk struct {
	config
	err      error
	builders []*AwardCreate
}

// Save creates the Award entities in the database.
func (_c *AwardCreateBulk) Save(ctx context.Context) ([]*Award, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Award, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AwardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AwardCreateBulk) SaveX(ctx context.Context) []*Award {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AwardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AwardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
