// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/award"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/nominee"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/predicate"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/schema"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/school"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/voteitem"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/votingsession"
)

// AwardUpdate is the builder for updating Award entities.
type AwardUpdate struct {
	config
	hooks    []Hook
	mutation *AwardMutation
}

// Where appends a list predicates to the AwardUpdate builder.
func (_u *AwardUpdate) Where(ps ...predicate.Award) *AwardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AwardUpdate) SetUpdatedAt(v time.Time) *AwardUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AwardUpdate) SetName(v string) *AwardUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AwardUpdate) SetNillableName(v *string) *AwardUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AwardUpdate) SetDescription(v string) *AwardUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AwardUpdate) SetNillableDescription(v *string) *AwardUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AwardUpdate) ClearDescription() *AwardUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCategory sets the "category" field.
func (_u *AwardUpdate) SetCategory(v award.Category) *AwardUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *AwardUpdate) SetNillableCategory(v *award.Category) *AwardUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetScoreConfig sets the "score_config" field.
func (_u *AwardUpdate) SetScoreConfig(v schema.ScoreConfig) *AwardUpdate {
	_u.mutation.SetScoreConfig(v)
	return _u
}

// SetNillableScoreConfig sets the "score_config" field if the given value is not nil.
func (_u *AwardUpdate) SetNillableScoreConfig(v *schema.ScoreConfig) *AwardUpdate {
	if v != nil {
		_u.SetScoreConfig(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *AwardUpdate) SetDisplayOrder(v int) *AwardUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *AwardUpdate) SetNillableDisplayOrder(v *int) *AwardUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *AwardUpdate) AddDisplayOrder(v int) *AwardUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetSessionID sets the "session" edge to the VotingSession entity by ID.
func (_u *AwardUpdate) SetSessionID(id uuid.UUID) *AwardUpdate {
	_u.mutation.SetSessionID(id)
	return _u
}

// SetSession sets the "session" edge to the VotingSession entity.
func (_u *AwardUpdate) SetSession(v *VotingSession) *AwardUpdate {
	return _u.SetSessionID(v.ID)
}

// SetSchoolID sets the "school" edge to the School entity by ID.
func (_u *AwardUpdate) SetSchoolID(id uuid.UUID) *AwardUpdate {
	_u.mutation.SetSchoolID(id)
	return _u
}

// SetNillableSchoolID sets the "school" edge to the School entity by ID if the given value is not nil.
func (_u *AwardUpdate) SetNillableSchoolID(id *uuid.UUID) *AwardUpdate {
	if id != nil {
		_u = _u.SetSchoolID(*id)
	}
	return _u
}

// SetSchool sets the "school" edge to the School entity.
func (_u *AwardUpdate) SetSchool(v *School) *AwardUpdate {
	return _u.SetSchoolID(v.ID)
}

// AddNomineeIDs adds the "nominees" edge to the Nominee entity by IDs.
func (_u *AwardUpdate) AddNomineeIDs(ids ...uuid.UUID) *AwardUpdate {
	_u.mutation.AddNomineeIDs(ids...)
	return _u
}

// AddNominees adds the "nominees" edges to the Nominee entity.
func (_u *AwardUpdate) AddNominees(v ...*Nominee) *AwardUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNomineeIDs(ids...)
}

// AddVoteItemIDs adds the "vote_items" edge to the VoteItem entity by IDs.
func (_u *AwardUpdate) AddVoteItemIDs(ids ...uuid.UUID) *AwardUpdate {
	_u.mutation.AddVoteItemIDs(ids...)
	return _u
}

// AddVoteItems adds the "vote_items" edges to the VoteItem entity.
func (_u *AwardUpdate) AddVoteItems(v ...*VoteItem) *AwardUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteItemIDs(ids...)
}

// Mutation returns the AwardMutation object of the builder.
func (_u *AwardUpdate) Mutation() *AwardMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the VotingSession entity.
func (_u *AwardUpdate) ClearSession() *AwardUpdate {
	_u.mutation.ClearSession()
	return _u
}

// ClearSchool clears the "school" edge to the School entity.
func (_u *AwardUpdate) ClearSchool() *AwardUpdate {
	_u.mutation.ClearSchool()
	return _u
}

// ClearNominees clears all "nominees" edges to the Nominee entity.
func (_u *AwardUpdate) ClearNominees() *AwardUpdate {
	_u.mutation.ClearNominees()
	return _u
}

// RemoveNomineeIDs removes the "nominees" edge to Nominee entities by IDs.
func (_u *AwardUpdate) RemoveNomineeIDs(ids ...uuid.UUID) *AwardUpdate {
	_u.mutation.RemoveNomineeIDs(ids...)
	return _u
}

// RemoveNominees removes "nominees" edges to Nominee entities.
func (_u *AwardUpdate) RemoveNominees(v ...*Nominee) *AwardUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNomineeIDs(ids...)
}

// ClearVoteItems clears all "vote_items" edges to the VoteItem entity.
func (_u *AwardUpdate) ClearVoteItems() *AwardUpdate {
	_u.mutation.ClearVoteItems()
	return _u
}

// RemoveVoteItemIDs removes the "vote_items" edge to VoteItem entities by IDs.
func (_u *AwardUpdate) RemoveVoteItemIDs(ids ...uuid.UUID) *AwardUpdate {
	_u.mutation.RemoveVoteItemIDs(ids...)
	return _u
}

// RemoveVoteItems removes "vote_items" edges to VoteItem entities.
func (_u *AwardUpdate) RemoveVoteItems(v ...*VoteItem) *AwardUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AwardUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AwardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AwardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AwardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AwardUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := award.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AwardUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := award.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Award.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := award.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Award.category": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Award.session"`)
	}
	return nil
}

func (_u *AwardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(award.Table, award.Columns, sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(award.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(award.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(award.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(award.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(award.FieldCategory, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScoreConfig(); ok {
		_spec.SetField(award.FieldScoreConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(award.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(award.FieldDisplayOrder, field.TypeInt, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   award.SessionTable,
			Columns: []string{award.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   award.SessionTable,
			Columns: []string{award.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SchoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   award.SchoolTable,
			Columns: []string{award.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SchoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   award.SchoolTable,
			Columns: []string{award.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NomineesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.NomineesTable,
			Columns: []string{award.NomineesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNomineesIDs(); len(nodes) > 0 && !_u.mutation.NomineesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.NomineesTable,
			Columns: []string{award.NomineesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NomineesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.NomineesTable,
			Columns: []string{award.NomineesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.VoteItemsTable,
			Columns: []string{award.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVoteItemsIDs(); len(nodes) > 0 && !_u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.VoteItemsTable,
			Columns: []string{award.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VoteItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.VoteItemsTable,
			Columns: []string{award.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{award.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AwardUpdateOne is the builder for updating a single Award entity.
type AwardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AwardMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AwardUpdateOne) SetUpdatedAt(v time.Time) *AwardUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AwardUpdateOne) SetName(v string) *AwardUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AwardUpdateOne) SetNillableName(v *string) *AwardUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AwardUpdateOne) SetDescription(v string) *AwardUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AwardUpdateOne) SetNillableDescription(v *string) *AwardUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AwardUpdateOne) ClearDescription() *AwardUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCategory sets the "category" field.
func (_u *AwardUpdateOne) SetCategory(v award.Category) *AwardUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *AwardUpdateOne) SetNillableCategory(v *award.Category) *AwardUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetScoreConfig sets the "score_config" field.
func (_u *AwardUpdateOne) SetScoreConfig(v schema.ScoreConfig) *AwardUpdateOne {
	_u.mutation.SetScoreConfig(v)
	return _u
}

// SetNillableScoreConfig sets the "score_config" field if the given value is not nil.
func (_u *AwardUpdateOne) SetNillableScoreConfig(v *schema.ScoreConfig) *AwardUpdateOne {
	if v != nil {
		_u.SetScoreConfig(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *AwardUpdateOne) SetDisplayOrder(v int) *AwardUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *AwardUpdateOne) SetNillableDisplayOrder(v *int) *AwardUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *AwardUpdateOne) AddDisplayOrder(v int) *AwardUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetSessionID sets the "session" edge to the VotingSession entity by ID.
func (_u *AwardUpdateOne) SetSessionID(id uuid.UUID) *AwardUpdateOne {
	_u.mutation.SetSessionID(id)
	return _u
}

// SetSession sets the "session" edge to the VotingSession entity.
func (_u *AwardUpdateOne) SetSession(v *VotingSession) *AwardUpdateOne {
	return _u.SetSessionID(v.ID)
}

// SetSchoolID sets the "school" edge to the School entity by ID.
func (_u *AwardUpdateOne) SetSchoolID(id uuid.UUID) *AwardUpdateOne {
	_u.mutation.SetSchoolID(id)
	return _u
}

// SetNillableSchoolID sets the "school" edge to the School entity by ID if the given value is not nil.
func (_u *AwardUpdateOne) SetNillableSchoolID(id *uuid.UUID) *AwardUpdateOne {
	if id != nil {
		_u = _u.SetSchoolID(*id)
	}
	return _u
}

// SetSchool sets the "school" edge to the School entity.
func (_u *AwardUpdateOne) SetSchool(v *School) *AwardUpdateOne {
	return _u.SetSchoolID(v.ID)
}

// AddNomineeIDs adds the "nominees" edge to the Nominee entity by IDs.
func (_u *AwardUpdateOne) AddNomineeIDs(ids ...uuid.UUID) *AwardUpdateOne {
	_u.mutation.AddNomineeIDs(ids...)
	return _u
}

// AddNominees adds the "nominees" edges to the Nominee entity.
func (_u *AwardUpdateOne) AddNominees(v ...*Nominee) *AwardUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNomineeIDs(ids...)
}

// AddVoteItemIDs adds the "vote_items" edge to the VoteItem entity by IDs.
func (_u *AwardUpdateOne) AddVoteItemIDs(ids ...uuid.UUID) *AwardUpdateOne {
	_u.mutation.AddVoteItemIDs(ids...)
	return _u
}

// AddVoteItems adds the "vote_items" edges to the VoteItem entity.
func (_u *AwardUpdateOne) AddVoteItems(v ...*VoteItem) *AwardUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteItemIDs(ids...)
}

// Mutation returns the AwardMutation object of the builder.
func (_u *AwardUpdateOne) Mutation() *AwardMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the VotingSession entity.
func (_u *AwardUpdateOne) ClearSession() *AwardUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// ClearSchool clears the "school" edge to the School entity.
func (_u *AwardUpdateOne) ClearSchool() *AwardUpdateOne {
	_u.mutation.ClearSchool()
	return _u
}

// ClearNominees clears all "nominees" edges to the Nominee entity.
func (_u *AwardUpdateOne) ClearNominees() *AwardUpdateOne {
	_u.mutation.ClearNominees()
	return _u
}

// RemoveNomineeIDs removes the "nominees" edge to Nominee entities by IDs.
func (_u *AwardUpdateOne) RemoveNomineeIDs(ids ...uuid.UUID) *AwardUpdateOne {
	_u.mutation.RemoveNomineeIDs(ids...)
	return _u
}

// RemoveNominees removes "nominees" edges to Nominee entities.
func (_u *AwardUpdateOne) RemoveNominees(v ...*Nominee) *AwardUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNomineeIDs(ids...)
}

// ClearVoteItems clears all "vote_items" edges to the VoteItem entity.
func (_u *AwardUpdateOne) ClearVoteItems() *AwardUpdateOne {
	_u.mutation.ClearVoteItems()
	return _u
}

// RemoveVoteItemIDs removes the "vote_items" edge to VoteItem entities by IDs.
func (_u *AwardUpdateOne) RemoveVoteItemIDs(ids ...uuid.UUID) *AwardUpdateOne {
	_u.mutation.RemoveVoteItemIDs(ids...)
	return _u
}

// RemoveVoteItems removes "vote_items" edges to VoteItem entities.
func (_u *AwardUpdateOne) RemoveVoteItems(v ...*VoteItem) *AwardUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteItemIDs(ids...)
}

// Where appends a list predicates to the AwardUpdate builder.
func (_u *AwardUpdateOne) Where(ps ...predicate.Award) *AwardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AwardUpdateOne) Select(field string, fields ...string) *AwardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Award entity.
func (_u *AwardUpdateOne) Save(ctx context.Context) (*Award, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AwardUpdateOne) SaveX(ctx context.Context) *Award {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AwardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AwardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AwardUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := award.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AwardUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := award.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Award.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := award.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Award.category": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Award.session"`)
	}
	return nil
}

func (_u *AwardUpdateOne) sqlSave(ctx context.Context) (_node *Award, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(award.Table, award.Columns, sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Award.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, award.FieldID)
		for _, f := range fields {
			if !award.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != award.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(award.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(award.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(award.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(award.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(award.FieldCategory, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScoreConfig(); ok {
		_spec.SetField(award.FieldScoreConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(award.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(award.FieldDisplayOrder, field.TypeInt, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   award.SessionTable,
			Columns: []string{award.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   award.SessionTable,
			Columns: []string{award.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SchoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   award.SchoolTable,
			Columns: []string{award.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SchoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   award.SchoolTable,
			Columns: []string{award.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NomineesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.NomineesTable,
			Columns: []string{award.NomineesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNomineesIDs(); len(nodes) > 0 && !_u.mutation.NomineesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.NomineesTable,
			Columns: []string{award.NomineesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NomineesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.NomineesTable,
			Columns: []string{award.NomineesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.VoteItemsTable,
			Columns: []string{award.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVoteItemsIDs(); len(nodes) > 0 && !_u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.VoteItemsTable,
			Columns: []string{award.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VoteItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   award.VoteItemsTable,
			Columns: []string{award.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Award{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{award.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
