// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/award"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/schema"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/school"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/votingsession"
)

// Award is the model entity for the Award schema.
type Award struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Category holds the value of the "category" field.
	Category award.Category `json:"category,omitempty"`
	// ScoreConfig holds the value of the "score_config" field.
	ScoreConfig schema.ScoreConfig `json:"score_config,omitempty"`
	// DisplayOrder holds the value of the "display_order" field.
	DisplayOrder int `json:"display_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AwardQuery when eager-loading is set.
	Edges                 AwardEdges `json:"edges"`
	school_awards         *uuid.UUID
	voting_session_awards *uuid.UUID
	selectValues          sql.SelectValues
}

// AwardEdges holds the relations/edges for other nodes in the graph.
type AwardEdges struct {
	// Session holds the value of the session edge.
	Session *VotingSession `json:"session,omitempty"`
	// School holds the value of the school edge.
	School *School `json:"school,omitempty"`
	// Nominees holds the value of the nominees edge.
	Nominees []*Nominee `json:"nominees,omitempty"`
	// VoteItems holds the value of the vote_items edge.
	VoteItems []*VoteItem `json:"vote_items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AwardEdges) SessionOrErr() (*VotingSession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: votingsession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// SchoolOrErr returns the School value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AwardEdges) SchoolOrErr() (*School, error) {
	if e.School != nil {
		return e.School, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: school.Label}
	}
	return nil, &NotLoadedError{edge: "school"}
}

// NomineesOrErr returns the Nominees value or an error if the edge
// was not loaded in eager-loading.
func (e AwardEdges) NomineesOrErr() ([]*Nominee, error) {
	if e.loadedTypes[2] {
		return e.Nominees, nil
	}
	return nil, &NotLoadedError{edge: "nominees"}
}

// VoteItemsOrErr returns the VoteItems value or an error if the edge
// was not loaded in eager-loading.
func (e AwardEdges) VoteItemsOrErr() ([]*VoteItem, error) {
	if e.loadedTypes[3] {
		return e.VoteItems, nil
	}
	return nil, &NotLoadedError{edge: "vote_items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Award) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case award.FieldScoreConfig:
			values[i] = new([]byte)
		case award.FieldDisplayOrder:
			values[i] = new(sql.NullInt64)
		case award.FieldName, award.FieldDescription, award.FieldCategory:
			values[i] = new(sql.NullString)
		case award.FieldCreatedAt, award.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case award.FieldID:
			values[i] = new(uuid.UUID)
		case award.ForeignKeys[0]: // school_awards
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case award.ForeignKeys[1]: // voting_session_awards
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Award fields.
func (_m *Award) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case award.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case award.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case award.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case award.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case award.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case award.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = award.Category(value.String)
			}
		case award.FieldScoreConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field score_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ScoreConfig); err != nil {
					return fmt.Errorf("unmarshal field score_config: %w", err)
				}
			}
		case award.FieldDisplayOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field display_order", values[i])
			} else if value.Valid {
				_m.DisplayOrder = int(value.Int64)
			}
		case award.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field school_awards", values[i])
			} else if value.Valid {
				_m.school_awards = new(uuid.UUID)
				*_m.school_awards = *value.S.(*uuid.UUID)
			}
		case award.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field voting_session_awards", values[i])
			} else if value.Valid {
				_m.voting_session_awards = new(uuid.UUID)
				*_m.voting_session_awards = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Award.
// This includes values selected through modifiers, order, etc.
func (_m *Award) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the Award entity.
func (_m *Award) QuerySession() *VotingSessionQuery {
	return NewAwardClient(_m.config).QuerySession(_m)
}

// QuerySchool queries the "school" edge of the Award entity.
func (_m *Award) QuerySchool() *SchoolQuery {
	return NewAwardClient(_m.config).QuerySchool(_m)
}

// QueryNominees queries the "nominees" edge of the Award entity.
func (_m *Award) QueryNominees() *NomineeQuery {
	return NewAwardClient(_m.config).QueryNominees(_m)
}

// QueryVoteItems queries the "vote_items" edge of the Award entity.
func (_m *Award) QueryVoteItems() *VoteItemQuery {
	return NewAwardClient(_m.config).QueryVoteItems(_m)
}

// Update returns a builder for updating this Award.
// Note that you need to call Award.Unwrap() before calling this method if this Award
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Award) Update() *AwardUpdateOne {
	return NewAwardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Award entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Award) Unwrap() *Award {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Award is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Award) String() string {
	var builder strings.Builder
	builder.WriteString("Award(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(fmt.Sprintf("%v", _m.Category))
	builder.WriteString(", ")
	builder.WriteString("score_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScoreConfig))
	builder.WriteString(", ")
	builder.WriteString("display_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisplayOrder))
	builder.WriteByte(')')
	return builder.String()
}

// Awards is a parsable slice of Award.
type Awards []*Award
