// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/award"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/nominee"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/school"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/user"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/voteitem"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/votingsession"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Award is the client for interacting with the Award builders.
	Award *AwardClient
	// Nominee is the client for interacting with the Nominee builders.
	Nominee *NomineeClient
	// School is the client for interacting with the School builders.
	School *SchoolClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// VoteItem is the client for interacting with the VoteItem builders.
	VoteItem *VoteItemClient
	// VotingSession is the client for interacting with the VotingSession builders.
	VotingSession *VotingSessionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Award = NewAwardClient(c.config)
	c.Nominee = NewNomineeClient(c.config)
	c.School = NewSchoolClient(c.config)
	c.User = NewUserClient(c.config)
	c.VoteItem = NewVoteItemClient(c.config)
	c.VotingSession = NewVotingSessionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Award:         NewAwardClient(cfg),
		Nominee:       NewNomineeClient(cfg),
		School:        NewSchoolClient(cfg),
		User:          NewUserClient(cfg),
		VoteItem:      NewVoteItemClient(cfg),
		VotingSession: NewVotingSessionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Award:         NewAwardClient(cfg),
		Nominee:       NewNomineeClient(cfg),
		School:        NewSchoolClient(cfg),
		User:          NewUserClient(cfg),
		VoteItem:      NewVoteItemClient(cfg),
		VotingSession: NewVotingSessionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Award.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Award, c.Nominee, c.School, c.User, c.VoteItem, c.VotingSession,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Award, c.Nominee, c.School, c.User, c.VoteItem, c.VotingSession,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AwardMutation:
		return c.Award.mutate(ctx, m)
	case *NomineeMutation:
		return c.Nominee.mutate(ctx, m)
	case *SchoolMutation:
		return c.School.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *VoteItemMutation:
		return c.VoteItem.mutate(ctx, m)
	case *VotingSessionMutation:
		return c.VotingSession.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AwardClient is a client for the Award schema.
type AwardClient struct {
	config
}

// NewAwardClient returns a client for the Award from the given config.
func NewAwardClient(c config) *AwardClient {
	return &AwardClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `award.Hooks(f(g(h())))`.
func (c *AwardClient) Use(hooks ...Hook) {
	c.hooks.Award = append(c.hooks.Award, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `award.Intercept(f(g(h())))`.
func (c *AwardClient) Intercept(interceptors ...Interceptor) {
	c.inters.Award = append(c.inters.Award, interceptors...)
}

// Create returns a builder for creating a Award entity.
func (c *AwardClient) Create() *AwardCreate {
	mutation := newAwardMutation(c.config, OpCreate)
	return &AwardCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Award entities.
func (c *AwardClient) CreateBulk(builders ...*AwardCreate) *AwardCreateBulk {
	return &AwardCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AwardClient) MapCreateBulk(slice any, setFunc func(*AwardCreate, int)) *AwardCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AwardCreateBulk{err: fmt.Errorf("calling to AwardClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AwardCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AwardCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Award.
func (c *AwardClient) Update() *AwardUpdate {
	mutation := newAwardMutation(c.config, OpUpdate)
	return &AwardUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AwardClient) UpdateOne(_m *Award) *AwardUpdateOne {
	mutation := newAwardMutation(c.config, OpUpdateOne, withAward(_m))
	return &AwardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AwardClient) UpdateOneID(id uuid.UUID) *AwardUpdateOne {
	mutation := newAwardMutation(c.config, OpUpdateOne, withAwardID(id))
	return &AwardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Award.
func (c *AwardClient) Delete() *AwardDelete {
	mutation := newAwardMutation(c.config, OpDelete)
	return &AwardDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AwardClient) DeleteOne(_m *Award) *AwardDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AwardClient) DeleteOneID(id uuid.UUID) *AwardDeleteOne {
	builder := c.Delete().Where(award.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AwardDeleteOne{builder}
}

// Query returns a query builder for Award.
func (c *AwardClient) Query() *AwardQuery {
	return &AwardQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAward},
		inters: c.Interceptors(),
	}
}

// Get returns a Award entity by its id.
func (c *AwardClient) Get(ctx context.Context, id uuid.UUID) (*Award, error) {
	return c.Query().Where(award.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AwardClient) GetX(ctx context.Context, id uuid.UUID) *Award {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySession queries the session edge of a Award.
func (c *AwardClient) QuerySession(_m *Award) *VotingSessionQuery {
	query := (&VotingSessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(award.Table, award.FieldID, id),
			sqlgraph.To(votingsession.Table, votingsession.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, award.SessionTable, award.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySchool queries the school edge of a Award.
func (c *AwardClient) QuerySchool(_m *Award) *SchoolQuery {
	query := (&SchoolClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(award.Table, award.FieldID, id),
			sqlgraph.To(school.Table, school.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, award.SchoolTable, award.SchoolColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryNominees queries the nominees edge of a Award.
func (c *AwardClient) QueryNominees(_m *Award) *NomineeQuery {
	query := (&NomineeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(award.Table, award.FieldID, id),
			sqlgraph.To(nominee.Table, nominee.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, award.NomineesTable, award.NomineesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryVoteItems queries the vote_items edge of a Award.
func (c *AwardClient) QueryVoteItems(_m *Award) *VoteItemQuery {
	query := (&VoteItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(award.Table, award.FieldID, id),
			sqlgraph.To(voteitem.Table, voteitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, award.VoteItemsTable, award.VoteItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AwardClient) Hooks() []Hook {
	return c.hooks.Award
}

// Interceptors returns the client interceptors.
func (c *AwardClient) Interceptors() []Interceptor {
	return c.inters.Award
}

func (c *AwardClient) mutate(ctx context.Context, m *AwardMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AwardCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AwardUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AwardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AwardDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Award mutation op: %q", m.Op())
	}
}

// NomineeClient is a client for the Nominee schema.
type NomineeClient struct {
	config
}

// NewNomineeClient returns a client for the Nominee from the given config.
func NewNomineeClient(c config) *NomineeClient {
	return &NomineeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `nominee.Hooks(f(g(h())))`.
func (c *NomineeClient) Use(hooks ...Hook) {
	c.hooks.Nominee = append(c.hooks.Nominee, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `nominee.Intercept(f(g(h())))`.
func (c *NomineeClient) Intercept(interceptors ...Interceptor) {
	c.inters.Nominee = append(c.inters.Nominee, interceptors...)
}

// Create returns a builder for creating a Nominee entity.
func (c *NomineeClient) Create() *NomineeCreate {
	mutation := newNomineeMutation(c.config, OpCreate)
	return &NomineeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Nominee entities.
func (c *NomineeClient) CreateBulk(builders ...*NomineeCreate) *NomineeCreateBulk {
	return &NomineeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NomineeClient) MapCreateBulk(slice any, setFunc func(*NomineeCreate, int)) *NomineeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NomineeCreateBulk{err: fmt.Errorf("calling to NomineeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NomineeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NomineeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Nominee.
func (c *NomineeClient) Update() *NomineeUpdate {
	mutation := newNomineeMutation(c.config, OpUpdate)
	return &NomineeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NomineeClient) UpdateOne(_m *Nominee) *NomineeUpdateOne {
	mutation := newNomineeMutation(c.config, OpUpdateOne, withNominee(_m))
	return &NomineeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NomineeClient) UpdateOneID(id uuid.UUID) *NomineeUpdateOne {
	mutation := newNomineeMutation(c.config, OpUpdateOne, withNomineeID(id))
	return &NomineeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Nominee.
func (c *NomineeClient) Delete() *NomineeDelete {
	mutation := newNomineeMutation(c.config, OpDelete)
	return &NomineeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NomineeClient) DeleteOne(_m *Nominee) *NomineeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NomineeClient) DeleteOneID(id uuid.UUID) *NomineeDeleteOne {
	builder := c.Delete().Where(nominee.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NomineeDeleteOne{builder}
}

// Query returns a query builder for Nominee.
func (c *NomineeClient) Query() *NomineeQuery {
	return &NomineeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNominee},
		inters: c.Interceptors(),
	}
}

// Get returns a Nominee entity by its id.
func (c *NomineeClient) Get(ctx context.Context, id uuid.UUID) (*Nominee, error) {
	return c.Query().Where(nominee.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NomineeClient) GetX(ctx context.Context, id uuid.UUID) *Nominee {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAward queries the award edge of a Nominee.
func (c *NomineeClient) QueryAward(_m *Nominee) *AwardQuery {
	query := (&AwardClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(nominee.Table, nominee.FieldID, id),
			sqlgraph.To(award.Table, award.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, nominee.AwardTable, nominee.AwardColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryVoteItems queries the vote_items edge of a Nominee.
func (c *NomineeClient) QueryVoteItems(_m *Nominee) *VoteItemQuery {
	query := (&VoteItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(nominee.Table, nominee.FieldID, id),
			sqlgraph.To(voteitem.Table, voteitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, nominee.VoteItemsTable, nominee.VoteItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NomineeClient) Hooks() []Hook {
	return c.hooks.Nominee
}

// Interceptors returns the client interceptors.
func (c *NomineeClient) Interceptors() []Interceptor {
	return c.inters.Nominee
}

func (c *NomineeClient) mutate(ctx context.Context, m *NomineeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NomineeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NomineeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NomineeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NomineeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Nominee mutation op: %q", m.Op())
	}
}

// SchoolClient is a client for the School schema.
type SchoolClient struct {
	config
}

// NewSchoolClient returns a client for the School from the given config.
func NewSchoolClient(c config) *SchoolClient {
	return &SchoolClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `school.Hooks(f(g(h())))`.
func (c *SchoolClient) Use(hooks ...Hook) {
	c.hooks.School = append(c.hooks.School, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `school.Intercept(f(g(h())))`.
func (c *SchoolClient) Intercept(interceptors ...Interceptor) {
	c.inters.School = append(c.inters.School, interceptors...)
}

// Create returns a builder for creating a School entity.
func (c *SchoolClient) Create() *SchoolCreate {
	mutation := newSchoolMutation(c.config, OpCreate)
	return &SchoolCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of School entities.
func (c *SchoolClient) CreateBulk(builders ...*SchoolCreate) *SchoolCreateBulk {
	return &SchoolCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SchoolClient) MapCreateBulk(slice any, setFunc func(*SchoolCreate, int)) *SchoolCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SchoolCreateBulk{err: fmt.Errorf("calling to SchoolClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SchoolCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SchoolCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for School.
func (c *SchoolClient) Update() *SchoolUpdate {
	mutation := newSchoolMutation(c.config, OpUpdate)
	return &SchoolUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SchoolClient) UpdateOne(_m *School) *SchoolUpdateOne {
	mutation := newSchoolMutation(c.config, OpUpdateOne, withSchool(_m))
	return &SchoolUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SchoolClient) UpdateOneID(id uuid.UUID) *SchoolUpdateOne {
	mutation := newSchoolMutation(c.config, OpUpdateOne, withSchoolID(id))
	return &SchoolUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for School.
func (c *SchoolClient) Delete() *SchoolDelete {
	mutation := newSchoolMutation(c.config, OpDelete)
	return &SchoolDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SchoolClient) DeleteOne(_m *School) *SchoolDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SchoolClient) DeleteOneID(id uuid.UUID) *SchoolDeleteOne {
	builder := c.Delete().Where(school.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SchoolDeleteOne{builder}
}

// Query returns a query builder for School.
func (c *SchoolClient) Query() *SchoolQuery {
	return &SchoolQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSchool},
		inters: c.Interceptors(),
	}
}

// Get returns a School entity by its id.
func (c *SchoolClient) Get(ctx context.Context, id uuid.UUID) (*School, error) {
	return c.Query().Where(school.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SchoolClient) GetX(ctx context.Context, id uuid.UUID) *School {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUsers queries the users edge of a School.
func (c *SchoolClient) QueryUsers(_m *School) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(school.Table, school.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, school.UsersTable, school.UsersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAwards queries the awards edge of a School.
func (c *SchoolClient) QueryAwards(_m *School) *AwardQuery {
	query := (&AwardClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(school.Table, school.FieldID, id),
			sqlgraph.To(award.Table, award.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, school.AwardsTable, school.AwardsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryVoteItems queries the vote_items edge of a School.
func (c *SchoolClient) QueryVoteItems(_m *School) *VoteItemQuery {
	query := (&VoteItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(school.Table, school.FieldID, id),
			sqlgraph.To(voteitem.Table, voteitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, school.VoteItemsTable, school.VoteItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SchoolClient) Hooks() []Hook {
	return c.hooks.School
}

// Interceptors returns the client interceptors.
func (c *SchoolClient) Interceptors() []Interceptor {
	return c.inters.School
}

func (c *SchoolClient) mutate(ctx context.Context, m *SchoolMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SchoolCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SchoolUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SchoolUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SchoolDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown School mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySchool queries the school edge of a User.
func (c *UserClient) QuerySchool(_m *User) *SchoolQuery {
	query := (&SchoolClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(school.Table, school.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, user.SchoolTable, user.SchoolColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryVoteItems queries the vote_items edge of a User.
func (c *UserClient) QueryVoteItems(_m *User) *VoteItemQuery {
	query := (&VoteItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(voteitem.Table, voteitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.VoteItemsTable, user.VoteItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// VoteItemClient is a client for the VoteItem schema.
type VoteItemClient struct {
	config
}

// NewVoteItemClient returns a client for the VoteItem from the given config.
func NewVoteItemClient(c config) *VoteItemClient {
	return &VoteItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `voteitem.Hooks(f(g(h())))`.
func (c *VoteItemClient) Use(hooks ...Hook) {
	c.hooks.VoteItem = append(c.hooks.VoteItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `voteitem.Intercept(f(g(h())))`.
func (c *VoteItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.VoteItem = append(c.inters.VoteItem, interceptors...)
}

// Create returns a builder for creating a VoteItem entity.
func (c *VoteItemClient) Create() *VoteItemCreate {
	mutation := newVoteItemMutation(c.config, OpCreate)
	return &VoteItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of VoteItem entities.
func (c *VoteItemClient) CreateBulk(builders ...*VoteItemCreate) *VoteItemCreateBulk {
	return &VoteItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *VoteItemClient) MapCreateBulk(slice any, setFunc func(*VoteItemCreate, int)) *VoteItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &VoteItemCreateBulk{err: fmt.Errorf("calling to VoteItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*VoteItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &VoteItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for VoteItem.
func (c *VoteItemClient) Update() *VoteItemUpdate {
	mutation := newVoteItemMutation(c.config, OpUpdate)
	return &VoteItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VoteItemClient) UpdateOne(_m *VoteItem) *VoteItemUpdateOne {
	mutation := newVoteItemMutation(c.config, OpUpdateOne, withVoteItem(_m))
	return &VoteItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VoteItemClient) UpdateOneID(id uuid.UUID) *VoteItemUpdateOne {
	mutation := newVoteItemMutation(c.config, OpUpdateOne, withVoteItemID(id))
	return &VoteItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for VoteItem.
func (c *VoteItemClient) Delete() *VoteItemDelete {
	mutation := newVoteItemMutation(c.config, OpDelete)
	return &VoteItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *VoteItemClient) DeleteOne(_m *VoteItem) *VoteItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *VoteItemClient) DeleteOneID(id uuid.UUID) *VoteItemDeleteOne {
	builder := c.Delete().Where(voteitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VoteItemDeleteOne{builder}
}

// Query returns a query builder for VoteItem.
func (c *VoteItemClient) Query() *VoteItemQuery {
	return &VoteItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeVoteItem},
		inters: c.Interceptors(),
	}
}

// Get returns a VoteItem entity by its id.
func (c *VoteItemClient) Get(ctx context.Context, id uuid.UUID) (*VoteItem, error) {
	return c.Query().Where(voteitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VoteItemClient) GetX(ctx context.Context, id uuid.UUID) *VoteItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a VoteItem.
func (c *VoteItemClient) QueryUser(_m *VoteItem) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(voteitem.Table, voteitem.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, voteitem.UserTable, voteitem.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySession queries the session edge of a VoteItem.
func (c *VoteItemClient) QuerySession(_m *VoteItem) *VotingSessionQuery {
	query := (&VotingSessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(voteitem.Table, voteitem.FieldID, id),
			sqlgraph.To(votingsession.Table, votingsession.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, voteitem.SessionTable, voteitem.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySchool queries the school edge of a VoteItem.
func (c *VoteItemClient) QuerySchool(_m *VoteItem) *SchoolQuery {
	query := (&SchoolClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(voteitem.Table, voteitem.FieldID, id),
			sqlgraph.To(school.Table, school.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, voteitem.SchoolTable, voteitem.SchoolColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAward queries the award edge of a VoteItem.
func (c *VoteItemClient) QueryAward(_m *VoteItem) *AwardQuery {
	query := (&AwardClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(voteitem.Table, voteitem.FieldID, id),
			sqlgraph.To(award.Table, award.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, voteitem.AwardTable, voteitem.AwardColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryNominee queries the nominee edge of a VoteItem.
func (c *VoteItemClient) QueryNominee(_m *VoteItem) *NomineeQuery {
	query := (&NomineeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(voteitem.Table, voteitem.FieldID, id),
			sqlgraph.To(nominee.Table, nominee.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, voteitem.NomineeTable, voteitem.NomineeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *VoteItemClient) Hooks() []Hook {
	return c.hooks.VoteItem
}

// Interceptors returns the client interceptors.
func (c *VoteItemClient) Interceptors() []Interceptor {
	return c.inters.VoteItem
}

func (c *VoteItemClient) mutate(ctx context.Context, m *VoteItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&VoteItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&VoteItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&VoteItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&VoteItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown VoteItem mutation op: %q", m.Op())
	}
}

// VotingSessionClient is a client for the VotingSession schema.
type VotingSessionClient struct {
	config
}

// NewVotingSessionClient returns a client for the VotingSession from the given config.
func NewVotingSessionClient(c config) *VotingSessionClient {
	return &VotingSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `votingsession.Hooks(f(g(h())))`.
func (c *VotingSessionClient) Use(hooks ...Hook) {
	c.hooks.VotingSession = append(c.hooks.VotingSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `votingsession.Intercept(f(g(h())))`.
func (c *VotingSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.VotingSession = append(c.inters.VotingSession, interceptors...)
}

// Create returns a builder for creating a VotingSession entity.
func (c *VotingSessionClient) Create() *VotingSessionCreate {
	mutation := newVotingSessionMutation(c.config, OpCreate)
	return &VotingSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of VotingSession entities.
func (c *VotingSessionClient) CreateBulk(builders ...*VotingSessionCreate) *VotingSessionCreateBulk {
	return &VotingSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *VotingSessionClient) MapCreateBulk(slice any, setFunc func(*VotingSessionCreate, int)) *VotingSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &VotingSessionCreateBulk{err: fmt.Errorf("calling to VotingSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*VotingSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &VotingSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for VotingSession.
func (c *VotingSessionClient) Update() *VotingSessionUpdate {
	mutation := newVotingSessionMutation(c.config, OpUpdate)
	return &VotingSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VotingSessionClient) UpdateOne(_m *VotingSession) *VotingSessionUpdateOne {
	mutation := newVotingSessionMutation(c.config, OpUpdateOne, withVotingSession(_m))
	return &VotingSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VotingSessionClient) UpdateOneID(id uuid.UUID) *VotingSessionUpdateOne {
	mutation := newVotingSessionMutation(c.config, OpUpdateOne, withVotingSessionID(id))
	return &VotingSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for VotingSession.
func (c *VotingSessionClient) Delete() *VotingSessionDelete {
	mutation := newVotingSessionMutation(c.config, OpDelete)
	return &VotingSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *VotingSessionClient) DeleteOne(_m *VotingSession) *VotingSessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *VotingSessionClient) DeleteOneID(id uuid.UUID) *VotingSessionDeleteOne {
	builder := c.Delete().Where(votingsession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VotingSessionDeleteOne{builder}
}

// Query returns a query builder for VotingSession.
func (c *VotingSessionClient) Query() *VotingSessionQuery {
	return &VotingSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeVotingSession},
		inters: c.Interceptors(),
	}
}

// Get returns a VotingSession entity by its id.
func (c *VotingSessionClient) Get(ctx context.Context, id uuid.UUID) (*VotingSession, error) {
	return c.Query().Where(votingsession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VotingSessionClient) GetX(ctx context.Context, id uuid.UUID) *VotingSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAwards queries the awards edge of a VotingSession.
func (c *VotingSessionClient) QueryAwards(_m *VotingSession) *AwardQuery {
	query := (&AwardClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(votingsession.Table, votingsession.FieldID, id),
			sqlgraph.To(award.Table, award.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, votingsession.AwardsTable, votingsession.AwardsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryVoteItems queries the vote_items edge of a VotingSession.
func (c *VotingSessionClient) QueryVoteItems(_m *VotingSession) *VoteItemQuery {
	query := (&VoteItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(votingsession.Table, votingsession.FieldID, id),
			sqlgraph.To(voteitem.Table, voteitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, votingsession.VoteItemsTable, votingsession.VoteItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *VotingSessionClient) Hooks() []Hook {
	return c.hooks.VotingSession
}

// Interceptors returns the client interceptors.
func (c *VotingSessionClient) Interceptors() []Interceptor {
	return c.inters.VotingSession
}

func (c *VotingSessionClient) mutate(ctx context.Context, m *VotingSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&VotingSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&VotingSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&VotingSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&VotingSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown VotingSession mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Award, Nominee, School, User, VoteItem, VotingSession []ent.Hook
	}
	inters struct {
		Award, Nominee, School, User, VoteItem, VotingSession []ent.Interceptor
	}
)
