// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/award"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/nominee"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/predicate"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/voteitem"
)

// NomineeUpdate is the builder for updating Nominee entities.
type NomineeUpdate struct {
	config
	hooks    []Hook
	mutation *NomineeMutation
}

// Where appends a list predicates to the NomineeUpdate builder.
func (_u *NomineeUpdate) Where(ps ...predicate.Nominee) *NomineeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NomineeUpdate) SetUpdatedAt(v time.Time) *NomineeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *NomineeUpdate) SetName(v string) *NomineeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NomineeUpdate) SetNillableName(v *string) *NomineeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCoverImageKey sets the "cover_image_key" field.
func (_u *NomineeUpdate) SetCoverImageKey(v string) *NomineeUpdate {
	_u.mutation.SetCoverImageKey(v)
	return _u
}

// SetNillableCoverImageKey sets the "cover_image_key" field if the given value is not nil.
func (_u *NomineeUpdate) SetNillableCoverImageKey(v *string) *NomineeUpdate {
	if v != nil {
		_u.SetCoverImageKey(*v)
	}
	return _u
}

// ClearCoverImageKey clears the value of the "cover_image_key" field.
func (_u *NomineeUpdate) ClearCoverImageKey() *NomineeUpdate {
	_u.mutation.ClearCoverImageKey()
	return _u
}

// SetDescription sets the "description" field.
func (_u *NomineeUpdate) SetDescription(v string) *NomineeUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *NomineeUpdate) SetNillableDescription(v *string) *NomineeUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *NomineeUpdate) ClearDescription() *NomineeUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *NomineeUpdate) SetDisplayOrder(v int) *NomineeUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *NomineeUpdate) SetNillableDisplayOrder(v *int) *NomineeUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *NomineeUpdate) AddDisplayOrder(v int) *NomineeUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetBangumiID sets the "bangumi_id" field.
func (_u *NomineeUpdate) SetBangumiID(v string) *NomineeUpdate {
	_u.mutation.SetBangumiID(v)
	return _u
}

// SetNillableBangumiID sets the "bangumi_id" field if the given value is not nil.
func (_u *NomineeUpdate) SetNillableBangumiID(v *string) *NomineeUpdate {
	if v != nil {
		_u.SetBangumiID(*v)
	}
	return _u
}

// ClearBangumiID clears the value of the "bangumi_id" field.
func (_u *NomineeUpdate) ClearBangumiID() *NomineeUpdate {
	_u.mutation.ClearBangumiID()
	return _u
}

// SetRelatedBangumiID sets the "related_bangumi_id" field.
func (_u *NomineeUpdate) SetRelatedBangumiID(v string) *NomineeUpdate {
	_u.mutation.SetRelatedBangumiID(v)
	return _u
}

// SetNillableRelatedBangumiID sets the "related_bangumi_id" field if the given value is not nil.
func (_u *NomineeUpdate) SetNillableRelatedBangumiID(v *string) *NomineeUpdate {
	if v != nil {
		_u.SetRelatedBangumiID(*v)
	}
	return _u
}

// ClearRelatedBangumiID clears the value of the "related_bangumi_id" field.
func (_u *NomineeUpdate) ClearRelatedBangumiID() *NomineeUpdate {
	_u.mutation.ClearRelatedBangumiID()
	return _u
}

// SetRelatedName sets the "related_name" field.
func (_u *NomineeUpdate) SetRelatedName(v string) *NomineeUpdate {
	_u.mutation.SetRelatedName(v)
	return _u
}

// SetNillableRelatedName sets the "related_name" field if the given value is not nil.
func (_u *NomineeUpdate) SetNillableRelatedName(v *string) *NomineeUpdate {
	if v != nil {
		_u.SetRelatedName(*v)
	}
	return _u
}

// ClearRelatedName clears the value of the "related_name" field.
func (_u *NomineeUpdate) ClearRelatedName() *NomineeUpdate {
	_u.mutation.ClearRelatedName()
	return _u
}

// SetRelatedImageURL sets the "related_image_url" field.
func (_u *NomineeUpdate) SetRelatedImageURL(v string) *NomineeUpdate {
	_u.mutation.SetRelatedImageURL(v)
	return _u
}

// SetNillableRelatedImageURL sets the "related_image_url" field if the given value is not nil.
func (_u *NomineeUpdate) SetNillableRelatedImageURL(v *string) *NomineeUpdate {
	if v != nil {
		_u.SetRelatedImageURL(*v)
	}
	return _u
}

// ClearRelatedImageURL clears the value of the "related_image_url" field.
func (_u *NomineeUpdate) ClearRelatedImageURL() *NomineeUpdate {
	_u.mutation.ClearRelatedImageURL()
	return _u
}

// SetAwardID sets the "award" edge to the Award entity by ID.
func (_u *NomineeUpdate) SetAwardID(id uuid.UUID) *NomineeUpdate {
	_u.mutation.SetAwardID(id)
	return _u
}

// SetAward sets the "award" edge to the Award entity.
func (_u *NomineeUpdate) SetAward(v *Award) *NomineeUpdate {
	return _u.SetAwardID(v.ID)
}

// AddVoteItemIDs adds the "vote_items" edge to the VoteItem entity by IDs.
func (_u *NomineeUpdate) AddVoteItemIDs(ids ...uuid.UUID) *NomineeUpdate {
	_u.mutation.AddVoteItemIDs(ids...)
	return _u
}

// AddVoteItems adds the "vote_items" edges to the VoteItem entity.
func (_u *NomineeUpdate) AddVoteItems(v ...*VoteItem) *NomineeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteItemIDs(ids...)
}

// Mutation returns the NomineeMutation object of the builder.
func (_u *NomineeUpdate) Mutation() *NomineeMutation {
	return _u.mutation
}

// ClearAward clears the "award" edge to the Award entity.
func (_u *NomineeUpdate) ClearAward() *NomineeUpdate {
	_u.mutation.ClearAward()
	return _u
}

// ClearVoteItems clears all "vote_items" edges to the VoteItem entity.
func (_u *NomineeUpdate) ClearVoteItems() *NomineeUpdate {
	_u.mutation.ClearVoteItems()
	return _u
}

// RemoveVoteItemIDs removes the "vote_items" edge to VoteItem entities by IDs.
func (_u *NomineeUpdate) RemoveVoteItemIDs(ids ...uuid.UUID) *NomineeUpdate {
	_u.mutation.RemoveVoteItemIDs(ids...)
	return _u
}

// RemoveVoteItems removes "vote_items" edges to VoteItem entities.
func (_u *NomineeUpdate) RemoveVoteItems(v ...*VoteItem) *NomineeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NomineeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NomineeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NomineeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NomineeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NomineeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := nominee.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NomineeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := nominee.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Nominee.name": %w`, err)}
		}
	}
	if _u.mutation.AwardCleared() && len(_u.mutation.AwardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Nominee.award"`)
	}
	return nil
}

func (_u *NomineeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nominee.Table, nominee.Columns, sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(nominee.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(nominee.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverImageKey(); ok {
		_spec.SetField(nominee.FieldCoverImageKey, field.TypeString, value)
	}
	if _u.mutation.CoverImageKeyCleared() {
		_spec.ClearField(nominee.FieldCoverImageKey, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(nominee.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(nominee.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(nominee.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(nominee.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BangumiID(); ok {
		_spec.SetField(nominee.FieldBangumiID, field.TypeString, value)
	}
	if _u.mutation.BangumiIDCleared() {
		_spec.ClearField(nominee.FieldBangumiID, field.TypeString)
	}
	if value, ok := _u.mutation.RelatedBangumiID(); ok {
		_spec.SetField(nominee.FieldRelatedBangumiID, field.TypeString, value)
	}
	if _u.mutation.RelatedBangumiIDCleared() {
		_spec.ClearField(nominee.FieldRelatedBangumiID, field.TypeString)
	}
	if value, ok := _u.mutation.RelatedName(); ok {
		_spec.SetField(nominee.FieldRelatedName, field.TypeString, value)
	}
	if _u.mutation.RelatedNameCleared() {
		_spec.ClearField(nominee.FieldRelatedName, field.TypeString)
	}
	if value, ok := _u.mutation.RelatedImageURL(); ok {
		_spec.SetField(nominee.FieldRelatedImageURL, field.TypeString, value)
	}
	if _u.mutation.RelatedImageURLCleared() {
		_spec.ClearField(nominee.FieldRelatedImageURL, field.TypeString)
	}
	if _u.mutation.AwardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nominee.AwardTable,
			Columns: []string{nominee.AwardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AwardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nominee.AwardTable,
			Columns: []string{nominee.AwardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   nominee.VoteItemsTable,
			Columns: []string{nominee.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVoteItemsIDs(); len(nodes) > 0 && !_u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   nominee.VoteItemsTable,
			Columns: []string{nominee.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VoteItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   nominee.VoteItemsTable,
			Columns: []string{nominee.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nominee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NomineeUpdateOne is the builder for updating a single Nominee entity.
type NomineeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NomineeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NomineeUpdateOne) SetUpdatedAt(v time.Time) *NomineeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *NomineeUpdateOne) SetName(v string) *NomineeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NomineeUpdateOne) SetNillableName(v *string) *NomineeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCoverImageKey sets the "cover_image_key" field.
func (_u *NomineeUpdateOne) SetCoverImageKey(v string) *NomineeUpdateOne {
	_u.mutation.SetCoverImageKey(v)
	return _u
}

// SetNillableCoverImageKey sets the "cover_image_key" field if the given value is not nil.
func (_u *NomineeUpdateOne) SetNillableCoverImageKey(v *string) *NomineeUpdateOne {
	if v != nil {
		_u.SetCoverImageKey(*v)
	}
	return _u
}

// ClearCoverImageKey clears the value of the "cover_image_key" field.
func (_u *NomineeUpdateOne) ClearCoverImageKey() *NomineeUpdateOne {
	_u.mutation.ClearCoverImageKey()
	return _u
}

// SetDescription sets the "description" field.
func (_u *NomineeUpdateOne) SetDescription(v string) *NomineeUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *NomineeUpdateOne) SetNillableDescription(v *string) *NomineeUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *NomineeUpdateOne) ClearDescription() *NomineeUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *NomineeUpdateOne) SetDisplayOrder(v int) *NomineeUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *NomineeUpdateOne) SetNillableDisplayOrder(v *int) *NomineeUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *NomineeUpdateOne) AddDisplayOrder(v int) *NomineeUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetBangumiID sets the "bangumi_id" field.
func (_u *NomineeUpdateOne) SetBangumiID(v string) *NomineeUpdateOne {
	_u.mutation.SetBangumiID(v)
	return _u
}

// SetNillableBangumiID sets the "bangumi_id" field if the given value is not nil.
func (_u *NomineeUpdateOne) SetNillableBangumiID(v *string) *NomineeUpdateOne {
	if v != nil {
		_u.SetBangumiID(*v)
	}
	return _u
}

// ClearBangumiID clears the value of the "bangumi_id" field.
func (_u *NomineeUpdateOne) ClearBangumiID() *NomineeUpdateOne {
	_u.mutation.ClearBangumiID()
	return _u
}

// SetRelatedBangumiID sets the "related_bangumi_id" field.
func (_u *NomineeUpdateOne) SetRelatedBangumiID(v string) *NomineeUpdateOne {
	_u.mutation.SetRelatedBangumiID(v)
	return _u
}

// SetNillableRelatedBangumiID sets the "related_bangumi_id" field if the given value is not nil.
func (_u *NomineeUpdateOne) SetNillableRelatedBangumiID(v *string) *NomineeUpdateOne {
	if v != nil {
		_u.SetRelatedBangumiID(*v)
	}
	return _u
}

// ClearRelatedBangumiID clears the value of the "related_bangumi_id" field.
func (_u *NomineeUpdateOne) ClearRelatedBangumiID() *NomineeUpdateOne {
	_u.mutation.ClearRelatedBangumiID()
	return _u
}

// SetRelatedName sets the "related_name" field.
func (_u *NomineeUpdateOne) SetRelatedName(v string) *NomineeUpdateOne {
	_u.mutation.SetRelatedName(v)
	return _u
}

// SetNillableRelatedName sets the "related_name" field if the given value is not nil.
func (_u *NomineeUpdateOne) SetNillableRelatedName(v *string) *NomineeUpdateOne {
	if v != nil {
		_u.SetRelatedName(*v)
	}
	return _u
}

// ClearRelatedName clears the value of the "related_name" field.
func (_u *NomineeUpdateOne) ClearRelatedName() *NomineeUpdateOne {
	_u.mutation.ClearRelatedName()
	return _u
}

// SetRelatedImageURL sets the "related_image_url" field.
func (_u *NomineeUpdateOne) SetRelatedImageURL(v string) *NomineeUpdateOne {
	_u.mutation.SetRelatedImageURL(v)
	return _u
}

// SetNillableRelatedImageURL sets the "related_image_url" field if the given value is not nil.
func (_u *NomineeUpdateOne) SetNillableRelatedImageURL(v *string) *NomineeUpdateOne {
	if v != nil {
		_u.SetRelatedImageURL(*v)
	}
	return _u
}

// ClearRelatedImageURL clears the value of the "related_image_url" field.
func (_u *NomineeUpdateOne) ClearRelatedImageURL() *NomineeUpdateOne {
	_u.mutation.ClearRelatedImageURL()
	return _u
}

// SetAwardID sets the "award" edge to the Award entity by ID.
func (_u *NomineeUpdateOne) SetAwardID(id uuid.UUID) *NomineeUpdateOne {
	_u.mutation.SetAwardID(id)
	return _u
}

// SetAward sets the "award" edge to the Award entity.
func (_u *NomineeUpdateOne) SetAward(v *Award) *NomineeUpdateOne {
	return _u.SetAwardID(v.ID)
}

// AddVoteItemIDs adds the "vote_items" edge to the VoteItem entity by IDs.
func (_u *NomineeUpdateOne) AddVoteItemIDs(ids ...uuid.UUID) *NomineeUpdateOne {
	_u.mutation.AddVoteItemIDs(ids...)
	return _u
}

// AddVoteItems adds the "vote_items" edges to the VoteItem entity.
func (_u *NomineeUpdateOne) AddVoteItems(v ...*VoteItem) *NomineeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteItemIDs(ids...)
}

// Mutation returns the NomineeMutation object of the builder.
func (_u *NomineeUpdateOne) Mutation() *NomineeMutation {
	return _u.mutation
}

// ClearAward clears the "award" edge to the Award entity.
func (_u *NomineeUpdateOne) ClearAward() *NomineeUpdateOne {
	_u.mutation.ClearAward()
	return _u
}

// ClearVoteItems clears all "vote_items" edges to the VoteItem entity.
func (_u *NomineeUpdateOne) ClearVoteItems() *NomineeUpdateOne {
	_u.mutation.ClearVoteItems()
	return _u
}

// RemoveVoteItemIDs removes the "vote_items" edge to VoteItem entities by IDs.
func (_u *NomineeUpdateOne) RemoveVoteItemIDs(ids ...uuid.UUID) *NomineeUpdateOne {
	_u.mutation.RemoveVoteItemIDs(ids...)
	return _u
}

// RemoveVoteItems removes "vote_items" edges to VoteItem entities.
func (_u *NomineeUpdateOne) RemoveVoteItems(v ...*VoteItem) *NomineeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteItemIDs(ids...)
}

// Where appends a list predicates to the NomineeUpdate builder.
func (_u *NomineeUpdateOne) Where(ps ...predicate.Nominee) *NomineeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NomineeUpdateOne) Select(field string, fields ...string) *NomineeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Nominee entity.
func (_u *NomineeUpdateOne) Save(ctx context.Context) (*Nominee, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NomineeUpdateOne) SaveX(ctx context.Context) *Nominee {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NomineeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NomineeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NomineeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := nominee.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NomineeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := nominee.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Nominee.name": %w`, err)}
		}
	}
	if _u.mutation.AwardCleared() && len(_u.mutation.AwardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Nominee.award"`)
	}
	return nil
}

func (_u *NomineeUpdateOne) sqlSave(ctx context.Context) (_node *Nominee, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nominee.Table, nominee.Columns, sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Nominee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nominee.FieldID)
		for _, f := range fields {
			if !nominee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != nominee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(nominee.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(nominee.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverImageKey(); ok {
		_spec.SetField(nominee.FieldCoverImageKey, field.TypeString, value)
	}
	if _u.mutation.CoverImageKeyCleared() {
		_spec.ClearField(nominee.FieldCoverImageKey, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(nominee.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(nominee.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(nominee.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(nominee.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BangumiID(); ok {
		_spec.SetField(nominee.FieldBangumiID, field.TypeString, value)
	}
	if _u.mutation.BangumiIDCleared() {
		_spec.ClearField(nominee.FieldBangumiID, field.TypeString)
	}
	if value, ok := _u.mutation.RelatedBangumiID(); ok {
		_spec.SetField(nominee.FieldRelatedBangumiID, field.TypeString, value)
	}
	if _u.mutation.RelatedBangumiIDCleared() {
		_spec.ClearField(nominee.FieldRelatedBangumiID, field.TypeString)
	}
	if value, ok := _u.mutation.RelatedName(); ok {
		_spec.SetField(nominee.FieldRelatedName, field.TypeString, value)
	}
	if _u.mutation.RelatedNameCleared() {
		_spec.ClearField(nominee.FieldRelatedName, field.TypeString)
	}
	if value, ok := _u.mutation.RelatedImageURL(); ok {
		_spec.SetField(nominee.FieldRelatedImageURL, field.TypeString, value)
	}
	if _u.mutation.RelatedImageURLCleared() {
		_spec.ClearField(nominee.FieldRelatedImageURL, field.TypeString)
	}
	if _u.mutation.AwardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nominee.AwardTable,
			Columns: []string{nominee.AwardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AwardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nominee.AwardTable,
			Columns: []string{nominee.AwardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   nominee.VoteItemsTable,
			Columns: []string{nominee.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVoteItemsIDs(); len(nodes) > 0 && !_u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   nominee.VoteItemsTable,
			Columns: []string{nominee.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VoteItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   nominee.VoteItemsTable,
			Columns: []string{nominee.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Nominee{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nominee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
