// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/award"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/nominee"
)

// Nominee is the model entity for the Nominee schema.
type Nominee struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CoverImageKey holds the value of the "cover_image_key" field.
	CoverImageKey string `json:"cover_image_key,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// DisplayOrder holds the value of the "display_order" field.
	DisplayOrder int `json:"display_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NomineeQuery when eager-loading is set.
	Edges          NomineeEdges `json:"edges"`
	award_nominees *uuid.UUID
	selectValues   sql.SelectValues
}

// NomineeEdges holds the relations/edges for other nodes in the graph.
type NomineeEdges struct {
	// Award holds the value of the award edge.
	Award *Award `json:"award,omitempty"`
	// VoteItems holds the value of the vote_items edge.
	VoteItems []*VoteItem `json:"vote_items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AwardOrErr returns the Award value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NomineeEdges) AwardOrErr() (*Award, error) {
	if e.Award != nil {
		return e.Award, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: award.Label}
	}
	return nil, &NotLoadedError{edge: "award"}
}

// VoteItemsOrErr returns the VoteItems value or an error if the edge
// was not loaded in eager-loading.
func (e NomineeEdges) VoteItemsOrErr() ([]*VoteItem, error) {
	if e.loadedTypes[1] {
		return e.VoteItems, nil
	}
	return nil, &NotLoadedError{edge: "vote_items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Nominee) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case nominee.FieldDisplayOrder:
			values[i] = new(sql.NullInt64)
		case nominee.FieldName, nominee.FieldCoverImageKey, nominee.FieldDescription:
			values[i] = new(sql.NullString)
		case nominee.FieldCreatedAt, nominee.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case nominee.FieldID:
			values[i] = new(uuid.UUID)
		case nominee.ForeignKeys[0]: // award_nominees
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Nominee fields.
func (_m *Nominee) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nominee.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case nominee.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case nominee.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case nominee.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case nominee.FieldCoverImageKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_image_key", values[i])
			} else if value.Valid {
				_m.CoverImageKey = value.String
			}
		case nominee.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case nominee.FieldDisplayOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field display_order", values[i])
			} else if value.Valid {
				_m.DisplayOrder = int(value.Int64)
			}
		case nominee.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field award_nominees", values[i])
			} else if value.Valid {
				_m.award_nominees = new(uuid.UUID)
				*_m.award_nominees = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Nominee.
// This includes values selected through modifiers, order, etc.
func (_m *Nominee) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAward queries the "award" edge of the Nominee entity.
func (_m *Nominee) QueryAward() *AwardQuery {
	return NewNomineeClient(_m.config).QueryAward(_m)
}

// QueryVoteItems queries the "vote_items" edge of the Nominee entity.
func (_m *Nominee) QueryVoteItems() *VoteItemQuery {
	return NewNomineeClient(_m.config).QueryVoteItems(_m)
}

// Update returns a builder for updating this Nominee.
// Note that you need to call Nominee.Unwrap() before calling this method if this Nominee
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Nominee) Update() *NomineeUpdateOne {
	return NewNomineeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Nominee entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Nominee) Unwrap() *Nominee {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Nominee is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Nominee) String() string {
	var builder strings.Builder
	builder.WriteString("Nominee(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("cover_image_key=")
	builder.WriteString(_m.CoverImageKey)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("display_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisplayOrder))
	builder.WriteByte(')')
	return builder.String()
}

// Nominees is a parsable slice of Nominee.
type Nominees []*Nominee
