// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/award"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/predicate"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/school"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/user"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/voteitem"
)

// SchoolUpdate is the builder for updating School entities.
type SchoolUpdate struct {
	config
	hooks    []Hook
	mutation *SchoolMutation
}

// Where appends a list predicates to the SchoolUpdate builder.
func (_u *SchoolUpdate) Where(ps ...predicate.School) *SchoolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SchoolUpdate) SetUpdatedAt(v time.Time) *SchoolUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SchoolUpdate) SetName(v string) *SchoolUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SchoolUpdate) SetNillableName(v *string) *SchoolUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *SchoolUpdate) SetCode(v string) *SchoolUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *SchoolUpdate) SetNillableCode(v *string) *SchoolUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetEmailSuffixes sets the "email_suffixes" field.
func (_u *SchoolUpdate) SetEmailSuffixes(v []string) *SchoolUpdate {
	_u.mutation.SetEmailSuffixes(v)
	return _u
}

// AppendEmailSuffixes appends value to the "email_suffixes" field.
func (_u *SchoolUpdate) AppendEmailSuffixes(v []string) *SchoolUpdate {
	_u.mutation.AppendEmailSuffixes(v)
	return _u
}

// ClearEmailSuffixes clears the value of the "email_suffixes" field.
func (_u *SchoolUpdate) ClearEmailSuffixes() *SchoolUpdate {
	_u.mutation.ClearEmailSuffixes()
	return _u
}

// SetVerificationQuestions sets the "verification_questions" field.
func (_u *SchoolUpdate) SetVerificationQuestions(v []map[string]string) *SchoolUpdate {
	_u.mutation.SetVerificationQuestions(v)
	return _u
}

// AppendVerificationQuestions appends value to the "verification_questions" field.
func (_u *SchoolUpdate) AppendVerificationQuestions(v []map[string]string) *SchoolUpdate {
	_u.mutation.AppendVerificationQuestions(v)
	return _u
}

// ClearVerificationQuestions clears the value of the "verification_questions" field.
func (_u *SchoolUpdate) ClearVerificationQuestions() *SchoolUpdate {
	_u.mutation.ClearVerificationQuestions()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *SchoolUpdate) SetIsActive(v bool) *SchoolUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *SchoolUpdate) SetNillableIsActive(v *bool) *SchoolUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *SchoolUpdate) AddUserIDs(ids ...uuid.UUID) *SchoolUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *SchoolUpdate) AddUsers(v ...*User) *SchoolUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddAwardIDs adds the "awards" edge to the Award entity by IDs.
func (_u *SchoolUpdate) AddAwardIDs(ids ...uuid.UUID) *SchoolUpdate {
	_u.mutation.AddAwardIDs(ids...)
	return _u
}

// AddAwards adds the "awards" edges to the Award entity.
func (_u *SchoolUpdate) AddAwards(v ...*Award) *SchoolUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAwardIDs(ids...)
}

// AddVoteItemIDs adds the "vote_items" edge to the VoteItem entity by IDs.
func (_u *SchoolUpdate) AddVoteItemIDs(ids ...uuid.UUID) *SchoolUpdate {
	_u.mutation.AddVoteItemIDs(ids...)
	return _u
}

// AddVoteItems adds the "vote_items" edges to the VoteItem entity.
func (_u *SchoolUpdate) AddVoteItems(v ...*VoteItem) *SchoolUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteItemIDs(ids...)
}

// Mutation returns the SchoolMutation object of the builder.
func (_u *SchoolUpdate) Mutation() *SchoolMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *SchoolUpdate) ClearUsers() *SchoolUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *SchoolUpdate) RemoveUserIDs(ids ...uuid.UUID) *SchoolUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *SchoolUpdate) RemoveUsers(v ...*User) *SchoolUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearAwards clears all "awards" edges to the Award entity.
func (_u *SchoolUpdate) ClearAwards() *SchoolUpdate {
	_u.mutation.ClearAwards()
	return _u
}

// RemoveAwardIDs removes the "awards" edge to Award entities by IDs.
func (_u *SchoolUpdate) RemoveAwardIDs(ids ...uuid.UUID) *SchoolUpdate {
	_u.mutation.RemoveAwardIDs(ids...)
	return _u
}

// RemoveAwards removes "awards" edges to Award entities.
func (_u *SchoolUpdate) RemoveAwards(v ...*Award) *SchoolUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAwardIDs(ids...)
}

// ClearVoteItems clears all "vote_items" edges to the VoteItem entity.
func (_u *SchoolUpdate) ClearVoteItems() *SchoolUpdate {
	_u.mutation.ClearVoteItems()
	return _u
}

// RemoveVoteItemIDs removes the "vote_items" edge to VoteItem entities by IDs.
func (_u *SchoolUpdate) RemoveVoteItemIDs(ids ...uuid.UUID) *SchoolUpdate {
	_u.mutation.RemoveVoteItemIDs(ids...)
	return _u
}

// RemoveVoteItems removes "vote_items" edges to VoteItem entities.
func (_u *SchoolUpdate) RemoveVoteItems(v ...*VoteItem) *SchoolUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SchoolUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchoolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SchoolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchoolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SchoolUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := school.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchoolUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := school.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "School.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := school.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "School.code": %w`, err)}
		}
	}
	return nil
}

func (_u *SchoolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(school.Table, school.Columns, sqlgraph.NewFieldSpec(school.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(school.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(school.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(school.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailSuffixes(); ok {
		_spec.SetField(school.FieldEmailSuffixes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmailSuffixes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, school.FieldEmailSuffixes, value)
		})
	}
	if _u.mutation.EmailSuffixesCleared() {
		_spec.ClearField(school.FieldEmailSuffixes, field.TypeJSON)
	}
	if value, ok := _u.mutation.VerificationQuestions(); ok {
		_spec.SetField(school.FieldVerificationQuestions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVerificationQuestions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, school.FieldVerificationQuestions, value)
		})
	}
	if _u.mutation.VerificationQuestionsCleared() {
		_spec.ClearField(school.FieldVerificationQuestions, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(school.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.UsersTable,
			Columns: []string{school.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.UsersTable,
			Columns: []string{school.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.UsersTable,
			Columns: []string{school.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.AwardsTable,
			Columns: []string{school.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAwardsIDs(); len(nodes) > 0 && !_u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.AwardsTable,
			Columns: []string{school.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AwardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.AwardsTable,
			Columns: []string{school.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.VoteItemsTable,
			Columns: []string{school.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVoteItemsIDs(); len(nodes) > 0 && !_u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.VoteItemsTable,
			Columns: []string{school.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VoteItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.VoteItemsTable,
			Columns: []string{school.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{school.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SchoolUpdateOne is the builder for updating a single School entity.
type SchoolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SchoolMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SchoolUpdateOne) SetUpdatedAt(v time.Time) *SchoolUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SchoolUpdateOne) SetName(v string) *SchoolUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SchoolUpdateOne) SetNillableName(v *string) *SchoolUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *SchoolUpdateOne) SetCode(v string) *SchoolUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *SchoolUpdateOne) SetNillableCode(v *string) *SchoolUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetEmailSuffixes sets the "email_suffixes" field.
func (_u *SchoolUpdateOne) SetEmailSuffixes(v []string) *SchoolUpdateOne {
	_u.mutation.SetEmailSuffixes(v)
	return _u
}

// AppendEmailSuffixes appends value to the "email_suffixes" field.
func (_u *SchoolUpdateOne) AppendEmailSuffixes(v []string) *SchoolUpdateOne {
	_u.mutation.AppendEmailSuffixes(v)
	return _u
}

// ClearEmailSuffixes clears the value of the "email_suffixes" field.
func (_u *SchoolUpdateOne) ClearEmailSuffixes() *SchoolUpdateOne {
	_u.mutation.ClearEmailSuffixes()
	return _u
}

// SetVerificationQuestions sets the "verification_questions" field.
func (_u *SchoolUpdateOne) SetVerificationQuestions(v []map[string]string) *SchoolUpdateOne {
	_u.mutation.SetVerificationQuestions(v)
	return _u
}

// AppendVerificationQuestions appends value to the "verification_questions" field.
func (_u *SchoolUpdateOne) AppendVerificationQuestions(v []map[string]string) *SchoolUpdateOne {
	_u.mutation.AppendVerificationQuestions(v)
	return _u
}

// ClearVerificationQuestions clears the value of the "verification_questions" field.
func (_u *SchoolUpdateOne) ClearVerificationQuestions() *SchoolUpdateOne {
	_u.mutation.ClearVerificationQuestions()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *SchoolUpdateOne) SetIsActive(v bool) *SchoolUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *SchoolUpdateOne) SetNillableIsActive(v *bool) *SchoolUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *SchoolUpdateOne) AddUserIDs(ids ...uuid.UUID) *SchoolUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *SchoolUpdateOne) AddUsers(v ...*User) *SchoolUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddAwardIDs adds the "awards" edge to the Award entity by IDs.
func (_u *SchoolUpdateOne) AddAwardIDs(ids ...uuid.UUID) *SchoolUpdateOne {
	_u.mutation.AddAwardIDs(ids...)
	return _u
}

// AddAwards adds the "awards" edges to the Award entity.
func (_u *SchoolUpdateOne) AddAwards(v ...*Award) *SchoolUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAwardIDs(ids...)
}

// AddVoteItemIDs adds the "vote_items" edge to the VoteItem entity by IDs.
func (_u *SchoolUpdateOne) AddVoteItemIDs(ids ...uuid.UUID) *SchoolUpdateOne {
	_u.mutation.AddVoteItemIDs(ids...)
	return _u
}

// AddVoteItems adds the "vote_items" edges to the VoteItem entity.
func (_u *SchoolUpdateOne) AddVoteItems(v ...*VoteItem) *SchoolUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteItemIDs(ids...)
}

// Mutation returns the SchoolMutation object of the builder.
func (_u *SchoolUpdateOne) Mutation() *SchoolMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *SchoolUpdateOne) ClearUsers() *SchoolUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *SchoolUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *SchoolUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *SchoolUpdateOne) RemoveUsers(v ...*User) *SchoolUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearAwards clears all "awards" edges to the Award entity.
func (_u *SchoolUpdateOne) ClearAwards() *SchoolUpdateOne {
	_u.mutation.ClearAwards()
	return _u
}

// RemoveAwardIDs removes the "awards" edge to Award entities by IDs.
func (_u *SchoolUpdateOne) RemoveAwardIDs(ids ...uuid.UUID) *SchoolUpdateOne {
	_u.mutation.RemoveAwardIDs(ids...)
	return _u
}

// RemoveAwards removes "awards" edges to Award entities.
func (_u *SchoolUpdateOne) RemoveAwards(v ...*Award) *SchoolUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAwardIDs(ids...)
}

// ClearVoteItems clears all "vote_items" edges to the VoteItem entity.
func (_u *SchoolUpdateOne) ClearVoteItems() *SchoolUpdateOne {
	_u.mutation.ClearVoteItems()
	return _u
}

// RemoveVoteItemIDs removes the "vote_items" edge to VoteItem entities by IDs.
func (_u *SchoolUpdateOne) RemoveVoteItemIDs(ids ...uuid.UUID) *SchoolUpdateOne {
	_u.mutation.RemoveVoteItemIDs(ids...)
	return _u
}

// RemoveVoteItems removes "vote_items" edges to VoteItem entities.
func (_u *SchoolUpdateOne) RemoveVoteItems(v ...*VoteItem) *SchoolUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteItemIDs(ids...)
}

// Where appends a list predicates to the SchoolUpdate builder.
func (_u *SchoolUpdateOne) Where(ps ...predicate.School) *SchoolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SchoolUpdateOne) Select(field string, fields ...string) *SchoolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated School entity.
func (_u *SchoolUpdateOne) Save(ctx context.Context) (*School, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchoolUpdateOne) SaveX(ctx context.Context) *School {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SchoolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchoolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SchoolUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := school.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchoolUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := school.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "School.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := school.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "School.code": %w`, err)}
		}
	}
	return nil
}

func (_u *SchoolUpdateOne) sqlSave(ctx context.Context) (_node *School, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(school.Table, school.Columns, sqlgraph.NewFieldSpec(school.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "School.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, school.FieldID)
		for _, f := range fields {
			if !school.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != school.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(school.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(school.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(school.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailSuffixes(); ok {
		_spec.SetField(school.FieldEmailSuffixes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmailSuffixes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, school.FieldEmailSuffixes, value)
		})
	}
	if _u.mutation.EmailSuffixesCleared() {
		_spec.ClearField(school.FieldEmailSuffixes, field.TypeJSON)
	}
	if value, ok := _u.mutation.VerificationQuestions(); ok {
		_spec.SetField(school.FieldVerificationQuestions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVerificationQuestions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, school.FieldVerificationQuestions, value)
		})
	}
	if _u.mutation.VerificationQuestionsCleared() {
		_spec.ClearField(school.FieldVerificationQuestions, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(school.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.UsersTable,
			Columns: []string{school.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.UsersTable,
			Columns: []string{school.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.UsersTable,
			Columns: []string{school.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.AwardsTable,
			Columns: []string{school.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAwardsIDs(); len(nodes) > 0 && !_u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.AwardsTable,
			Columns: []string{school.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AwardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.AwardsTable,
			Columns: []string{school.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.VoteItemsTable,
			Columns: []string{school.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVoteItemsIDs(); len(nodes) > 0 && !_u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.VoteItemsTable,
			Columns: []string{school.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VoteItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.VoteItemsTable,
			Columns: []string{school.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &School{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{school.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
