// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/award"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/nominee"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/school"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/user"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/voteitem"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/votingsession"
)

// VoteItem is the model entity for the VoteItem schema.
type VoteItem struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Score holds the value of the "score" field.
	Score int `json:"score,omitempty"`
	// IPAddress holds the value of the "ip_address" field.
	IPAddress string `json:"ip_address,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent string `json:"user_agent,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VoteItemQuery when eager-loading is set.
	Edges                     VoteItemEdges `json:"edges"`
	award_vote_items          *uuid.UUID
	nominee_vote_items        *uuid.UUID
	school_vote_items         *uuid.UUID
	user_vote_items           *uuid.UUID
	voting_session_vote_items *uuid.UUID
	selectValues              sql.SelectValues
}

// VoteItemEdges holds the relations/edges for other nodes in the graph.
type VoteItemEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Session holds the value of the session edge.
	Session *VotingSession `json:"session,omitempty"`
	// School holds the value of the school edge.
	School *School `json:"school,omitempty"`
	// Award holds the value of the award edge.
	Award *Award `json:"award,omitempty"`
	// Nominee holds the value of the nominee edge.
	Nominee *Nominee `json:"nominee,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VoteItemEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VoteItemEdges) SessionOrErr() (*VotingSession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: votingsession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// SchoolOrErr returns the School value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VoteItemEdges) SchoolOrErr() (*School, error) {
	if e.School != nil {
		return e.School, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: school.Label}
	}
	return nil, &NotLoadedError{edge: "school"}
}

// AwardOrErr returns the Award value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VoteItemEdges) AwardOrErr() (*Award, error) {
	if e.Award != nil {
		return e.Award, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: award.Label}
	}
	return nil, &NotLoadedError{edge: "award"}
}

// NomineeOrErr returns the Nominee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VoteItemEdges) NomineeOrErr() (*Nominee, error) {
	if e.Nominee != nil {
		return e.Nominee, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: nominee.Label}
	}
	return nil, &NotLoadedError{edge: "nominee"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VoteItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case voteitem.FieldScore:
			values[i] = new(sql.NullInt64)
		case voteitem.FieldIPAddress, voteitem.FieldUserAgent:
			values[i] = new(sql.NullString)
		case voteitem.FieldCreatedAt, voteitem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case voteitem.FieldID:
			values[i] = new(uuid.UUID)
		case voteitem.ForeignKeys[0]: // award_vote_items
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case voteitem.ForeignKeys[1]: // nominee_vote_items
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case voteitem.ForeignKeys[2]: // school_vote_items
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case voteitem.ForeignKeys[3]: // user_vote_items
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case voteitem.ForeignKeys[4]: // voting_session_vote_items
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VoteItem fields.
func (_m *VoteItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case voteitem.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case voteitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case voteitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case voteitem.FieldScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = int(value.Int64)
			}
		case voteitem.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				_m.IPAddress = value.String
			}
		case voteitem.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case voteitem.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field award_vote_items", values[i])
			} else if value.Valid {
				_m.award_vote_items = new(uuid.UUID)
				*_m.award_vote_items = *value.S.(*uuid.UUID)
			}
		case voteitem.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field nominee_vote_items", values[i])
			} else if value.Valid {
				_m.nominee_vote_items = new(uuid.UUID)
				*_m.nominee_vote_items = *value.S.(*uuid.UUID)
			}
		case voteitem.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field school_vote_items", values[i])
			} else if value.Valid {
				_m.school_vote_items = new(uuid.UUID)
				*_m.school_vote_items = *value.S.(*uuid.UUID)
			}
		case voteitem.ForeignKeys[3]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_vote_items", values[i])
			} else if value.Valid {
				_m.user_vote_items = new(uuid.UUID)
				*_m.user_vote_items = *value.S.(*uuid.UUID)
			}
		case voteitem.ForeignKeys[4]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field voting_session_vote_items", values[i])
			} else if value.Valid {
				_m.voting_session_vote_items = new(uuid.UUID)
				*_m.voting_session_vote_items = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VoteItem.
// This includes values selected through modifiers, order, etc.
func (_m *VoteItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the VoteItem entity.
func (_m *VoteItem) QueryUser() *UserQuery {
	return NewVoteItemClient(_m.config).QueryUser(_m)
}

// QuerySession queries the "session" edge of the VoteItem entity.
func (_m *VoteItem) QuerySession() *VotingSessionQuery {
	return NewVoteItemClient(_m.config).QuerySession(_m)
}

// QuerySchool queries the "school" edge of the VoteItem entity.
func (_m *VoteItem) QuerySchool() *SchoolQuery {
	return NewVoteItemClient(_m.config).QuerySchool(_m)
}

// QueryAward queries the "award" edge of the VoteItem entity.
func (_m *VoteItem) QueryAward() *AwardQuery {
	return NewVoteItemClient(_m.config).QueryAward(_m)
}

// QueryNominee queries the "nominee" edge of the VoteItem entity.
func (_m *VoteItem) QueryNominee() *NomineeQuery {
	return NewVoteItemClient(_m.config).QueryNominee(_m)
}

// Update returns a builder for updating this VoteItem.
// Note that you need to call VoteItem.Unwrap() before calling this method if this VoteItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VoteItem) Update() *VoteItemUpdateOne {
	return NewVoteItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VoteItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VoteItem) Unwrap() *VoteItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VoteItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VoteItem) String() string {
	var builder strings.Builder
	builder.WriteString("VoteItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("ip_address=")
	builder.WriteString(_m.IPAddress)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteByte(')')
	return builder.String()
}

// VoteItems is a parsable slice of VoteItem.
type VoteItems []*VoteItem
