// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/award"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/nominee"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/predicate"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/school"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/user"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/voteitem"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/votingsession"
)

// VoteItemUpdate is the builder for updating VoteItem entities.
type VoteItemUpdate struct {
	config
	hooks    []Hook
	mutation *VoteItemMutation
}

// Where appends a list predicates to the VoteItemUpdate builder.
func (_u *VoteItemUpdate) Where(ps ...predicate.VoteItem) *VoteItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VoteItemUpdate) SetUpdatedAt(v time.Time) *VoteItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *VoteItemUpdate) SetScore(v int) *VoteItemUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *VoteItemUpdate) SetNillableScore(v *int) *VoteItemUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *VoteItemUpdate) AddScore(v int) *VoteItemUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *VoteItemUpdate) SetIPAddress(v string) *VoteItemUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *VoteItemUpdate) SetNillableIPAddress(v *string) *VoteItemUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *VoteItemUpdate) ClearIPAddress() *VoteItemUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *VoteItemUpdate) SetUserAgent(v string) *VoteItemUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *VoteItemUpdate) SetNillableUserAgent(v *string) *VoteItemUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *VoteItemUpdate) ClearUserAgent() *VoteItemUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *VoteItemUpdate) SetUserID(id uuid.UUID) *VoteItemUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *VoteItemUpdate) SetUser(v *User) *VoteItemUpdate {
	return _u.SetUserID(v.ID)
}

// SetSessionID sets the "session" edge to the VotingSession entity by ID.
func (_u *VoteItemUpdate) SetSessionID(id uuid.UUID) *VoteItemUpdate {
	_u.mutation.SetSessionID(id)
	return _u
}

// SetSession sets the "session" edge to the VotingSession entity.
func (_u *VoteItemUpdate) SetSession(v *VotingSession) *VoteItemUpdate {
	return _u.SetSessionID(v.ID)
}

// SetSchoolID sets the "school" edge to the School entity by ID.
func (_u *VoteItemUpdate) SetSchoolID(id uuid.UUID) *VoteItemUpdate {
	_u.mutation.SetSchoolID(id)
	return _u
}

// SetSchool sets the "school" edge to the School entity.
func (_u *VoteItemUpdate) SetSchool(v *School) *VoteItemUpdate {
	return _u.SetSchoolID(v.ID)
}

// SetAwardID sets the "award" edge to the Award entity by ID.
func (_u *VoteItemUpdate) SetAwardID(id uuid.UUID) *VoteItemUpdate {
	_u.mutation.SetAwardID(id)
	return _u
}

// SetAward sets the "award" edge to the Award entity.
func (_u *VoteItemUpdate) SetAward(v *Award) *VoteItemUpdate {
	return _u.SetAwardID(v.ID)
}

// SetNomineeID sets the "nominee" edge to the Nominee entity by ID.
func (_u *VoteItemUpdate) SetNomineeID(id uuid.UUID) *VoteItemUpdate {
	_u.mutation.SetNomineeID(id)
	return _u
}

// SetNominee sets the "nominee" edge to the Nominee entity.
func (_u *VoteItemUpdate) SetNominee(v *Nominee) *VoteItemUpdate {
	return _u.SetNomineeID(v.ID)
}

// Mutation returns the VoteItemMutation object of the builder.
func (_u *VoteItemUpdate) Mutation() *VoteItemMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *VoteItemUpdate) ClearUser() *VoteItemUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearSession clears the "session" edge to the VotingSession entity.
func (_u *VoteItemUpdate) ClearSession() *VoteItemUpdate {
	_u.mutation.ClearSession()
	return _u
}

// ClearSchool clears the "school" edge to the School entity.
func (_u *VoteItemUpdate) ClearSchool() *VoteItemUpdate {
	_u.mutation.ClearSchool()
	return _u
}

// ClearAward clears the "award" edge to the Award entity.
func (_u *VoteItemUpdate) ClearAward() *VoteItemUpdate {
	_u.mutation.ClearAward()
	return _u
}

// ClearNominee clears the "nominee" edge to the Nominee entity.
func (_u *VoteItemUpdate) ClearNominee() *VoteItemUpdate {
	_u.mutation.ClearNominee()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VoteItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VoteItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VoteItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VoteItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VoteItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := voteitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VoteItemUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoteItem.user"`)
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoteItem.session"`)
	}
	if _u.mutation.SchoolCleared() && len(_u.mutation.SchoolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoteItem.school"`)
	}
	if _u.mutation.AwardCleared() && len(_u.mutation.AwardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoteItem.award"`)
	}
	if _u.mutation.NomineeCleared() && len(_u.mutation.NomineeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoteItem.nominee"`)
	}
	return nil
}

func (_u *VoteItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(voteitem.Table, voteitem.Columns, sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(voteitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(voteitem.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(voteitem.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(voteitem.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(voteitem.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(voteitem.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(voteitem.FieldUserAgent, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.UserTable,
			Columns: []string{voteitem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.UserTable,
			Columns: []string{voteitem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.SessionTable,
			Columns: []string{voteitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.SessionTable,
			Columns: []string{voteitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SchoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.SchoolTable,
			Columns: []string{voteitem.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SchoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.SchoolTable,
			Columns: []string{voteitem.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AwardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.AwardTable,
			Columns: []string{voteitem.AwardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AwardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.AwardTable,
			Columns: []string{voteitem.AwardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NomineeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.NomineeTable,
			Columns: []string{voteitem.NomineeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NomineeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.NomineeTable,
			Columns: []string{voteitem.NomineeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{voteitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VoteItemUpdateOne is the builder for updating a single VoteItem entity.
type VoteItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VoteItemMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VoteItemUpdateOne) SetUpdatedAt(v time.Time) *VoteItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *VoteItemUpdateOne) SetScore(v int) *VoteItemUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *VoteItemUpdateOne) SetNillableScore(v *int) *VoteItemUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *VoteItemUpdateOne) AddScore(v int) *VoteItemUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *VoteItemUpdateOne) SetIPAddress(v string) *VoteItemUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *VoteItemUpdateOne) SetNillableIPAddress(v *string) *VoteItemUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *VoteItemUpdateOne) ClearIPAddress() *VoteItemUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *VoteItemUpdateOne) SetUserAgent(v string) *VoteItemUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *VoteItemUpdateOne) SetNillableUserAgent(v *string) *VoteItemUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *VoteItemUpdateOne) ClearUserAgent() *VoteItemUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *VoteItemUpdateOne) SetUserID(id uuid.UUID) *VoteItemUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *VoteItemUpdateOne) SetUser(v *User) *VoteItemUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetSessionID sets the "session" edge to the VotingSession entity by ID.
func (_u *VoteItemUpdateOne) SetSessionID(id uuid.UUID) *VoteItemUpdateOne {
	_u.mutation.SetSessionID(id)
	return _u
}

// SetSession sets the "session" edge to the VotingSession entity.
func (_u *VoteItemUpdateOne) SetSession(v *VotingSession) *VoteItemUpdateOne {
	return _u.SetSessionID(v.ID)
}

// SetSchoolID sets the "school" edge to the School entity by ID.
func (_u *VoteItemUpdateOne) SetSchoolID(id uuid.UUID) *VoteItemUpdateOne {
	_u.mutation.SetSchoolID(id)
	return _u
}

// SetSchool sets the "school" edge to the School entity.
func (_u *VoteItemUpdateOne) SetSchool(v *School) *VoteItemUpdateOne {
	return _u.SetSchoolID(v.ID)
}

// SetAwardID sets the "award" edge to the Award entity by ID.
func (_u *VoteItemUpdateOne) SetAwardID(id uuid.UUID) *VoteItemUpdateOne {
	_u.mutation.SetAwardID(id)
	return _u
}

// SetAward sets the "award" edge to the Award entity.
func (_u *VoteItemUpdateOne) SetAward(v *Award) *VoteItemUpdateOne {
	return _u.SetAwardID(v.ID)
}

// SetNomineeID sets the "nominee" edge to the Nominee entity by ID.
func (_u *VoteItemUpdateOne) SetNomineeID(id uuid.UUID) *VoteItemUpdateOne {
	_u.mutation.SetNomineeID(id)
	return _u
}

// SetNominee sets the "nominee" edge to the Nominee entity.
func (_u *VoteItemUpdateOne) SetNominee(v *Nominee) *VoteItemUpdateOne {
	return _u.SetNomineeID(v.ID)
}

// Mutation returns the VoteItemMutation object of the builder.
func (_u *VoteItemUpdateOne) Mutation() *VoteItemMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *VoteItemUpdateOne) ClearUser() *VoteItemUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearSession clears the "session" edge to the VotingSession entity.
func (_u *VoteItemUpdateOne) ClearSession() *VoteItemUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// ClearSchool clears the "school" edge to the School entity.
func (_u *VoteItemUpdateOne) ClearSchool() *VoteItemUpdateOne {
	_u.mutation.ClearSchool()
	return _u
}

// ClearAward clears the "award" edge to the Award entity.
func (_u *VoteItemUpdateOne) ClearAward() *VoteItemUpdateOne {
	_u.mutation.ClearAward()
	return _u
}

// ClearNominee clears the "nominee" edge to the Nominee entity.
func (_u *VoteItemUpdateOne) ClearNominee() *VoteItemUpdateOne {
	_u.mutation.ClearNominee()
	return _u
}

// Where appends a list predicates to the VoteItemUpdate builder.
func (_u *VoteItemUpdateOne) Where(ps ...predicate.VoteItem) *VoteItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VoteItemUpdateOne) Select(field string, fields ...string) *VoteItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VoteItem entity.
func (_u *VoteItemUpdateOne) Save(ctx context.Context) (*VoteItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VoteItemUpdateOne) SaveX(ctx context.Context) *VoteItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VoteItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VoteItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VoteItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := voteitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VoteItemUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoteItem.user"`)
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoteItem.session"`)
	}
	if _u.mutation.SchoolCleared() && len(_u.mutation.SchoolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoteItem.school"`)
	}
	if _u.mutation.AwardCleared() && len(_u.mutation.AwardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoteItem.award"`)
	}
	if _u.mutation.NomineeCleared() && len(_u.mutation.NomineeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoteItem.nominee"`)
	}
	return nil
}

func (_u *VoteItemUpdateOne) sqlSave(ctx context.Context) (_node *VoteItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(voteitem.Table, voteitem.Columns, sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VoteItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, voteitem.FieldID)
		for _, f := range fields {
			if !voteitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != voteitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(voteitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(voteitem.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(voteitem.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(voteitem.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(voteitem.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(voteitem.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(voteitem.FieldUserAgent, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.UserTable,
			Columns: []string{voteitem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.UserTable,
			Columns: []string{voteitem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.SessionTable,
			Columns: []string{voteitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.SessionTable,
			Columns: []string{voteitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SchoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.SchoolTable,
			Columns: []string{voteitem.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SchoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.SchoolTable,
			Columns: []string{voteitem.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AwardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.AwardTable,
			Columns: []string{voteitem.AwardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AwardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.AwardTable,
			Columns: []string{voteitem.AwardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NomineeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.NomineeTable,
			Columns: []string{voteitem.NomineeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NomineeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteitem.NomineeTable,
			Columns: []string{voteitem.NomineeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nominee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VoteItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{voteitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
