// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/award"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/predicate"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/voteitem"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/votingsession"
)

// VotingSessionQuery is the builder for querying VotingSession entities.
type VotingSessionQuery struct {
	config
	ctx           *QueryContext
	order         []votingsession.OrderOption
	inters        []Interceptor
	predicates    []predicate.VotingSession
	withAwards    *AwardQuery
	withVoteItems *VoteItemQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VotingSessionQuery builder.
func (_q *VotingSessionQuery) Where(ps ...predicate.VotingSession) *VotingSessionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *VotingSessionQuery) Limit(limit int) *VotingSessionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *VotingSessionQuery) Offset(offset int) *VotingSessionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *VotingSessionQuery) Unique(unique bool) *VotingSessionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *VotingSessionQuery) Order(o ...votingsession.OrderOption) *VotingSessionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAwards chains the current query on the "awards" edge.
func (_q *VotingSessionQuery) QueryAwards() *AwardQuery {
	query := (&AwardClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(votingsession.Table, votingsession.FieldID, selector),
			sqlgraph.To(award.Table, award.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, votingsession.AwardsTable, votingsession.AwardsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVoteItems chains the current query on the "vote_items" edge.
func (_q *VotingSessionQuery) QueryVoteItems() *VoteItemQuery {
	query := (&VoteItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(votingsession.Table, votingsession.FieldID, selector),
			sqlgraph.To(voteitem.Table, voteitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, votingsession.VoteItemsTable, votingsession.VoteItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VotingSession entity from the query.
// Returns a *NotFoundError when no VotingSession was found.
func (_q *VotingSessionQuery) First(ctx context.Context) (*VotingSession, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{votingsession.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *VotingSessionQuery) FirstX(ctx context.Context) *VotingSession {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VotingSession ID from the query.
// Returns a *NotFoundError when no VotingSession ID was found.
func (_q *VotingSessionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{votingsession.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *VotingSessionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VotingSession entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VotingSession entity is found.
// Returns a *NotFoundError when no VotingSession entities are found.
func (_q *VotingSessionQuery) Only(ctx context.Context) (*VotingSession, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{votingsession.Label}
	default:
		return nil, &NotSingularError{votingsession.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *VotingSessionQuery) OnlyX(ctx context.Context) *VotingSession {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VotingSession ID in the query.
// Returns a *NotSingularError when more than one VotingSession ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *VotingSessionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{votingsession.Label}
	default:
		err = &NotSingularError{votingsession.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *VotingSessionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VotingSessions.
func (_q *VotingSessionQuery) All(ctx context.Context) ([]*VotingSession, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VotingSession, *VotingSessionQuery]()
	return withInterceptors[[]*VotingSession](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *VotingSessionQuery) AllX(ctx context.Context) []*VotingSession {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VotingSession IDs.
func (_q *VotingSessionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(votingsession.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *VotingSessionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *VotingSessionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*VotingSessionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *VotingSessionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *VotingSessionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *VotingSessionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VotingSessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *VotingSessionQuery) Clone() *VotingSessionQuery {
	if _q == nil {
		return nil
	}
	return &VotingSessionQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]votingsession.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.VotingSession{}, _q.predicates...),
		withAwards:    _q.withAwards.Clone(),
		withVoteItems: _q.withVoteItems.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAwards tells the query-builder to eager-load the nodes that are connected to
// the "awards" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VotingSessionQuery) WithAwards(opts ...func(*AwardQuery)) *VotingSessionQuery {
	query := (&AwardClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAwards = query
	return _q
}

// WithVoteItems tells the query-builder to eager-load the nodes that are connected to
// the "vote_items" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VotingSessionQuery) WithVoteItems(opts ...func(*VoteItemQuery)) *VotingSessionQuery {
	query := (&VoteItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVoteItems = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VotingSession.Query().
//		GroupBy(votingsession.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *VotingSessionQuery) GroupBy(field string, fields ...string) *VotingSessionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VotingSessionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = votingsession.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.VotingSession.Query().
//		Select(votingsession.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *VotingSessionQuery) Select(fields ...string) *VotingSessionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &VotingSessionSelect{VotingSessionQuery: _q}
	sbuild.label = votingsession.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VotingSessionSelect configured with the given aggregations.
func (_q *VotingSessionQuery) Aggregate(fns ...AggregateFunc) *VotingSessionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *VotingSessionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !votingsession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *VotingSessionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VotingSession, error) {
	var (
		nodes       = []*VotingSession{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withAwards != nil,
			_q.withVoteItems != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VotingSession).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VotingSession{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAwards; query != nil {
		if err := _q.loadAwards(ctx, query, nodes,
			func(n *VotingSession) { n.Edges.Awards = []*Award{} },
			func(n *VotingSession, e *Award) { n.Edges.Awards = append(n.Edges.Awards, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withVoteItems; query != nil {
		if err := _q.loadVoteItems(ctx, query, nodes,
			func(n *VotingSession) { n.Edges.VoteItems = []*VoteItem{} },
			func(n *VotingSession, e *VoteItem) { n.Edges.VoteItems = append(n.Edges.VoteItems, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *VotingSessionQuery) loadAwards(ctx context.Context, query *AwardQuery, nodes []*VotingSession, init func(*VotingSession), assign func(*VotingSession, *Award)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*VotingSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Award(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(votingsession.AwardsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.voting_session_awards
		if fk == nil {
			return fmt.Errorf(`foreign-key "voting_session_awards" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "voting_session_awards" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *VotingSessionQuery) loadVoteItems(ctx context.Context, query *VoteItemQuery, nodes []*VotingSession, init func(*VotingSession), assign func(*VotingSession, *VoteItem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*VotingSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.VoteItem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(votingsession.VoteItemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.voting_session_vote_items
		if fk == nil {
			return fmt.Errorf(`foreign-key "voting_session_vote_items" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "voting_session_vote_items" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *VotingSessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *VotingSessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(votingsession.Table, votingsession.Columns, sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, votingsession.FieldID)
		for i := range fields {
			if fields[i] != votingsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *VotingSessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(votingsession.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = votingsession.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VotingSessionGroupBy is the group-by builder for VotingSession entities.
type VotingSessionGroupBy struct {
	selector
	build *VotingSessionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *VotingSessionGroupBy) Aggregate(fns ...AggregateFunc) *VotingSessionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *VotingSessionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VotingSessionQuery, *VotingSessionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *VotingSessionGroupBy) sqlScan(ctx context.Context, root *VotingSessionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VotingSessionSelect is the builder for selecting fields of VotingSession entities.
type VotingSessionSelect struct {
	*VotingSessionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *VotingSessionSelect) Aggregate(fns ...AggregateFunc) *VotingSessionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *VotingSessionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VotingSessionQuery, *VotingSessionSelect](ctx, _s.VotingSessionQuery, _s, _s.inters, v)
}

func (_s *VotingSessionSelect) sqlScan(ctx context.Context, root *VotingSessionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
