// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/award"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/voteitem"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/votingsession"
)

// VotingSessionCreate is the builder for creating a VotingSession entity.
type VotingSessionCreate struct {
	config
	mutation *VotingSessionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *VotingSessionCreate) SetCreatedAt(v time.Time) *VotingSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VotingSessionCreate) SetNillableCreatedAt(v *time.Time) *VotingSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VotingSessionCreate) SetUpdatedAt(v time.Time) *VotingSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VotingSessionCreate) SetNillableUpdatedAt(v *time.Time) *VotingSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetYear sets the "year" field.
func (_c *VotingSessionCreate) SetYear(v int) *VotingSessionCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetName sets the "name" field.
func (_c *VotingSessionCreate) SetName(v string) *VotingSessionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *VotingSessionCreate) SetStatus(v votingsession.Status) *VotingSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VotingSessionCreate) SetNillableStatus(v *votingsession.Status) *VotingSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VotingSessionCreate) SetID(v uuid.UUID) *VotingSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *VotingSessionCreate) SetNillableID(v *uuid.UUID) *VotingSessionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddAwardIDs adds the "awards" edge to the Award entity by IDs.
func (_c *VotingSessionCreate) AddAwardIDs(ids ...uuid.UUID) *VotingSessionCreate {
	_c.mutation.AddAwardIDs(ids...)
	return _c
}

// AddAwards adds the "awards" edges to the Award entity.
func (_c *VotingSessionCreate) AddAwards(v ...*Award) *VotingSessionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAwardIDs(ids...)
}

// AddVoteItemIDs adds the "vote_items" edge to the VoteItem entity by IDs.
func (_c *VotingSessionCreate) AddVoteItemIDs(ids ...uuid.UUID) *VotingSessionCreate {
	_c.mutation.AddVoteItemIDs(ids...)
	return _c
}

// AddVoteItems adds the "vote_items" edges to the VoteItem entity.
func (_c *VotingSessionCreate) AddVoteItems(v ...*VoteItem) *VotingSessionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVoteItemIDs(ids...)
}

// Mutation returns the VotingSessionMutation object of the builder.
func (_c *VotingSessionCreate) Mutation() *VotingSessionMutation {
	return _c.mutation
}

// Save creates the VotingSession in the database.
func (_c *VotingSessionCreate) Save(ctx context.Context) (*VotingSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VotingSessionCreate) SaveX(ctx context.Context) *VotingSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VotingSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VotingSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VotingSessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := votingsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := votingsession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := votingsession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := votingsession.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VotingSessionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VotingSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VotingSession.updated_at"`)}
	}
	if _, ok := _c.mutation.Year(); !ok {
		return &ValidationError{Name: "year", err: errors.New(`ent: missing required field "VotingSession.year"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "VotingSession.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := votingsession.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VotingSession.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "VotingSession.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := votingsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VotingSession.status": %w`, err)}
		}
	}
	return nil
}

func (_c *VotingSessionCreate) sqlSave(ctx context.Context) (*VotingSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VotingSessionCreate) createSpec() (*VotingSession, *sqlgraph.CreateSpec) {
	var (
		_node = &VotingSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(votingsession.Table, sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(votingsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(votingsession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(votingsession.FieldYear, field.TypeInt, value)
		_node.Year = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(votingsession.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(votingsession.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.AwardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.AwardsTable,
			Columns: []string{votingsession.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VoteItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.VoteItemsTable,
			Columns: []string{votingsession.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VotingSessionCreateBulk is the builder for creating many VotingSession entities in bulk.
type VotingSessionCreateBulk struct {
	config
	err      error
	builders []*VotingSessionCreate
}

// Save creates the VotingSession entities in the database.
func (_c *VotingSessionCreateBulk) Save(ctx context.Context) ([]*VotingSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VotingSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VotingSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VotingSessionCreateBulk) SaveX(ctx context.Context) []*VotingSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VotingSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VotingSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
