// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/award"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/predicate"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/voteitem"
	"github.com/inscripoem/bta-voting-system/backend/internal/ent/votingsession"
)

// VotingSessionUpdate is the builder for updating VotingSession entities.
type VotingSessionUpdate struct {
	config
	hooks    []Hook
	mutation *VotingSessionMutation
}

// Where appends a list predicates to the VotingSessionUpdate builder.
func (_u *VotingSessionUpdate) Where(ps ...predicate.VotingSession) *VotingSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VotingSessionUpdate) SetUpdatedAt(v time.Time) *VotingSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetYear sets the "year" field.
func (_u *VotingSessionUpdate) SetYear(v int) *VotingSessionUpdate {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *VotingSessionUpdate) SetNillableYear(v *int) *VotingSessionUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *VotingSessionUpdate) AddYear(v int) *VotingSessionUpdate {
	_u.mutation.AddYear(v)
	return _u
}

// SetName sets the "name" field.
func (_u *VotingSessionUpdate) SetName(v string) *VotingSessionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VotingSessionUpdate) SetNillableName(v *string) *VotingSessionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *VotingSessionUpdate) SetStatus(v votingsession.Status) *VotingSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VotingSessionUpdate) SetNillableStatus(v *votingsession.Status) *VotingSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddAwardIDs adds the "awards" edge to the Award entity by IDs.
func (_u *VotingSessionUpdate) AddAwardIDs(ids ...uuid.UUID) *VotingSessionUpdate {
	_u.mutation.AddAwardIDs(ids...)
	return _u
}

// AddAwards adds the "awards" edges to the Award entity.
func (_u *VotingSessionUpdate) AddAwards(v ...*Award) *VotingSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAwardIDs(ids...)
}

// AddVoteItemIDs adds the "vote_items" edge to the VoteItem entity by IDs.
func (_u *VotingSessionUpdate) AddVoteItemIDs(ids ...uuid.UUID) *VotingSessionUpdate {
	_u.mutation.AddVoteItemIDs(ids...)
	return _u
}

// AddVoteItems adds the "vote_items" edges to the VoteItem entity.
func (_u *VotingSessionUpdate) AddVoteItems(v ...*VoteItem) *VotingSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteItemIDs(ids...)
}

// Mutation returns the VotingSessionMutation object of the builder.
func (_u *VotingSessionUpdate) Mutation() *VotingSessionMutation {
	return _u.mutation
}

// ClearAwards clears all "awards" edges to the Award entity.
func (_u *VotingSessionUpdate) ClearAwards() *VotingSessionUpdate {
	_u.mutation.ClearAwards()
	return _u
}

// RemoveAwardIDs removes the "awards" edge to Award entities by IDs.
func (_u *VotingSessionUpdate) RemoveAwardIDs(ids ...uuid.UUID) *VotingSessionUpdate {
	_u.mutation.RemoveAwardIDs(ids...)
	return _u
}

// RemoveAwards removes "awards" edges to Award entities.
func (_u *VotingSessionUpdate) RemoveAwards(v ...*Award) *VotingSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAwardIDs(ids...)
}

// ClearVoteItems clears all "vote_items" edges to the VoteItem entity.
func (_u *VotingSessionUpdate) ClearVoteItems() *VotingSessionUpdate {
	_u.mutation.ClearVoteItems()
	return _u
}

// RemoveVoteItemIDs removes the "vote_items" edge to VoteItem entities by IDs.
func (_u *VotingSessionUpdate) RemoveVoteItemIDs(ids ...uuid.UUID) *VotingSessionUpdate {
	_u.mutation.RemoveVoteItemIDs(ids...)
	return _u
}

// RemoveVoteItems removes "vote_items" edges to VoteItem entities.
func (_u *VotingSessionUpdate) RemoveVoteItems(v ...*VoteItem) *VotingSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VotingSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VotingSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VotingSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VotingSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VotingSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := votingsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VotingSessionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := votingsession.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VotingSession.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := votingsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VotingSession.status": %w`, err)}
		}
	}
	return nil
}

func (_u *VotingSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(votingsession.Table, votingsession.Columns, sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(votingsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(votingsession.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(votingsession.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(votingsession.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(votingsession.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.AwardsTable,
			Columns: []string{votingsession.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAwardsIDs(); len(nodes) > 0 && !_u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.AwardsTable,
			Columns: []string{votingsession.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AwardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.AwardsTable,
			Columns: []string{votingsession.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.VoteItemsTable,
			Columns: []string{votingsession.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVoteItemsIDs(); len(nodes) > 0 && !_u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.VoteItemsTable,
			Columns: []string{votingsession.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VoteItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.VoteItemsTable,
			Columns: []string{votingsession.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{votingsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VotingSessionUpdateOne is the builder for updating a single VotingSession entity.
type VotingSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VotingSessionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VotingSessionUpdateOne) SetUpdatedAt(v time.Time) *VotingSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetYear sets the "year" field.
func (_u *VotingSessionUpdateOne) SetYear(v int) *VotingSessionUpdateOne {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *VotingSessionUpdateOne) SetNillableYear(v *int) *VotingSessionUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *VotingSessionUpdateOne) AddYear(v int) *VotingSessionUpdateOne {
	_u.mutation.AddYear(v)
	return _u
}

// SetName sets the "name" field.
func (_u *VotingSessionUpdateOne) SetName(v string) *VotingSessionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VotingSessionUpdateOne) SetNillableName(v *string) *VotingSessionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *VotingSessionUpdateOne) SetStatus(v votingsession.Status) *VotingSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VotingSessionUpdateOne) SetNillableStatus(v *votingsession.Status) *VotingSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddAwardIDs adds the "awards" edge to the Award entity by IDs.
func (_u *VotingSessionUpdateOne) AddAwardIDs(ids ...uuid.UUID) *VotingSessionUpdateOne {
	_u.mutation.AddAwardIDs(ids...)
	return _u
}

// AddAwards adds the "awards" edges to the Award entity.
func (_u *VotingSessionUpdateOne) AddAwards(v ...*Award) *VotingSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAwardIDs(ids...)
}

// AddVoteItemIDs adds the "vote_items" edge to the VoteItem entity by IDs.
func (_u *VotingSessionUpdateOne) AddVoteItemIDs(ids ...uuid.UUID) *VotingSessionUpdateOne {
	_u.mutation.AddVoteItemIDs(ids...)
	return _u
}

// AddVoteItems adds the "vote_items" edges to the VoteItem entity.
func (_u *VotingSessionUpdateOne) AddVoteItems(v ...*VoteItem) *VotingSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteItemIDs(ids...)
}

// Mutation returns the VotingSessionMutation object of the builder.
func (_u *VotingSessionUpdateOne) Mutation() *VotingSessionMutation {
	return _u.mutation
}

// ClearAwards clears all "awards" edges to the Award entity.
func (_u *VotingSessionUpdateOne) ClearAwards() *VotingSessionUpdateOne {
	_u.mutation.ClearAwards()
	return _u
}

// RemoveAwardIDs removes the "awards" edge to Award entities by IDs.
func (_u *VotingSessionUpdateOne) RemoveAwardIDs(ids ...uuid.UUID) *VotingSessionUpdateOne {
	_u.mutation.RemoveAwardIDs(ids...)
	return _u
}

// RemoveAwards removes "awards" edges to Award entities.
func (_u *VotingSessionUpdateOne) RemoveAwards(v ...*Award) *VotingSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAwardIDs(ids...)
}

// ClearVoteItems clears all "vote_items" edges to the VoteItem entity.
func (_u *VotingSessionUpdateOne) ClearVoteItems() *VotingSessionUpdateOne {
	_u.mutation.ClearVoteItems()
	return _u
}

// RemoveVoteItemIDs removes the "vote_items" edge to VoteItem entities by IDs.
func (_u *VotingSessionUpdateOne) RemoveVoteItemIDs(ids ...uuid.UUID) *VotingSessionUpdateOne {
	_u.mutation.RemoveVoteItemIDs(ids...)
	return _u
}

// RemoveVoteItems removes "vote_items" edges to VoteItem entities.
func (_u *VotingSessionUpdateOne) RemoveVoteItems(v ...*VoteItem) *VotingSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteItemIDs(ids...)
}

// Where appends a list predicates to the VotingSessionUpdate builder.
func (_u *VotingSessionUpdateOne) Where(ps ...predicate.VotingSession) *VotingSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VotingSessionUpdateOne) Select(field string, fields ...string) *VotingSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VotingSession entity.
func (_u *VotingSessionUpdateOne) Save(ctx context.Context) (*VotingSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VotingSessionUpdateOne) SaveX(ctx context.Context) *VotingSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VotingSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VotingSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VotingSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := votingsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VotingSessionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := votingsession.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VotingSession.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := votingsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VotingSession.status": %w`, err)}
		}
	}
	return nil
}

func (_u *VotingSessionUpdateOne) sqlSave(ctx context.Context) (_node *VotingSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(votingsession.Table, votingsession.Columns, sqlgraph.NewFieldSpec(votingsession.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VotingSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, votingsession.FieldID)
		for _, f := range fields {
			if !votingsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != votingsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(votingsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(votingsession.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(votingsession.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(votingsession.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(votingsession.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.AwardsTable,
			Columns: []string{votingsession.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAwardsIDs(); len(nodes) > 0 && !_u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.AwardsTable,
			Columns: []string{votingsession.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AwardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.AwardsTable,
			Columns: []string{votingsession.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(award.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.VoteItemsTable,
			Columns: []string{votingsession.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVoteItemsIDs(); len(nodes) > 0 && !_u.mutation.VoteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.VoteItemsTable,
			Columns: []string{votingsession.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VoteItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votingsession.VoteItemsTable,
			Columns: []string{votingsession.VoteItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VotingSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{votingsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
