// Code generated by ent, DO NOT EDIT.

package award

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the award type in the database.
	Label = "award"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldScoreConfig holds the string denoting the score_config field in the database.
	FieldScoreConfig = "score_config"
	// FieldDisplayOrder holds the string denoting the display_order field in the database.
	FieldDisplayOrder = "display_order"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// EdgeSchool holds the string denoting the school edge name in mutations.
	EdgeSchool = "school"
	// EdgeNominees holds the string denoting the nominees edge name in mutations.
	EdgeNominees = "nominees"
	// EdgeVoteItems holds the string denoting the vote_items edge name in mutations.
	EdgeVoteItems = "vote_items"
	// Table holds the table name of the award in the database.
	Table = "awards"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "awards"
	// SessionInverseTable is the table name for the VotingSession entity.
	// It exists in this package in order to avoid circular dependency with the "votingsession" package.
	SessionInverseTable = "voting_sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "voting_session_awards"
	// SchoolTable is the table that holds the school relation/edge.
	SchoolTable = "awards"
	// SchoolInverseTable is the table name for the School entity.
	// It exists in this package in order to avoid circular dependency with the "school" package.
	SchoolInverseTable = "schools"
	// SchoolColumn is the table column denoting the school relation/edge.
	SchoolColumn = "school_awards"
	// NomineesTable is the table that holds the nominees relation/edge.
	NomineesTable = "nominees"
	// NomineesInverseTable is the table name for the Nominee entity.
	// It exists in this package in order to avoid circular dependency with the "nominee" package.
	NomineesInverseTable = "nominees"
	// NomineesColumn is the table column denoting the nominees relation/edge.
	NomineesColumn = "award_nominees"
	// VoteItemsTable is the table that holds the vote_items relation/edge.
	VoteItemsTable = "vote_items"
	// VoteItemsInverseTable is the table name for the VoteItem entity.
	// It exists in this package in order to avoid circular dependency with the "voteitem" package.
	VoteItemsInverseTable = "vote_items"
	// VoteItemsColumn is the table column denoting the vote_items relation/edge.
	VoteItemsColumn = "award_vote_items"
)

// Columns holds all SQL columns for award fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldDescription,
	FieldCategory,
	FieldScoreConfig,
	FieldDisplayOrder,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "awards"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"school_awards",
	"voting_session_awards",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDisplayOrder holds the default value on creation for the "display_order" field.
	DefaultDisplayOrder int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Category defines the type for the "category" enum field.
type Category string

// Category values.
const (
	CategoryMandatory     Category = "mandatory"
	CategoryOptional      Category = "optional"
	CategoryEntertainment Category = "entertainment"
)

func (c Category) String() string {
	return string(c)
}

// CategoryValidator is a validator for the "category" field enum values. It is called by the builders before save.
func CategoryValidator(c Category) error {
	switch c {
	case CategoryMandatory, CategoryOptional, CategoryEntertainment:
		return nil
	default:
		return fmt.Errorf("award: invalid enum value for category field: %q", c)
	}
}

// OrderOption defines the ordering options for the Award queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByDisplayOrder orders the results by the display_order field.
func ByDisplayOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayOrder, opts...).ToFunc()
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}

// BySchoolField orders the results by school field.
func BySchoolField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSchoolStep(), sql.OrderByField(field, opts...))
	}
}

// ByNomineesCount orders the results by nominees count.
func ByNomineesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNomineesStep(), opts...)
	}
}

// ByNominees orders the results by nominees terms.
func ByNominees(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNomineesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByVoteItemsCount orders the results by vote_items count.
func ByVoteItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVoteItemsStep(), opts...)
	}
}

// ByVoteItems orders the results by vote_items terms.
func ByVoteItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVoteItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
	)
}
func newSchoolStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SchoolInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SchoolTable, SchoolColumn),
	)
}
func newNomineesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NomineesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NomineesTable, NomineesColumn),
	)
}
func newVoteItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VoteItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VoteItemsTable, VoteItemsColumn),
	)
}
