// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Award is the predicate function for award builders.
type Award func(*sql.Selector)

// Nominee is the predicate function for nominee builders.
type Nominee func(*sql.Selector)

// School is the predicate function for school builders.
type School func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// VoteItem is the predicate function for voteitem builders.
type VoteItem func(*sql.Selector)

// VotingSession is the predicate function for votingsession builders.
type VotingSession func(*sql.Selector)
